[package]
name = "cross-crate-target-models"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default = ["sqlite"]
sqlite = ["graphql-orm/sqlite"]
postgres = ["graphql-orm/postgres"]
mssql = ["graphql-orm/mssql"]

[dependencies]
graphql-orm.workspace = true
async-graphql.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
