[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

[dependencies]
agql-auth = { git = "https://github.com/Dastari/agql-auth.git", rev = "d6b9cef663d52125c52f3fb90d4155ee25d34775", version = "0.13.0" }
async-graphql = { version = "7", features = ["dataloader", "uuid"] }
graphql-orm = { path = "../../../../", default-features = false, features = [
  "sqlite",
  "auth-agql",
  "resolver-case-pascal",
  "argument-case-pascal",
  "field-case-pascal",
] }
serde = { version = "1", features = ["derive"] }
