[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

[dependencies]
agql-auth = { git = "https://github.com/Dastari/agql-auth.git", rev = "1d2e9fe2e1576105212a7b340a11abf8cad0382d", version = "0.19.0" }
async-graphql = { version = "7", features = ["dataloader", "uuid"] }
graphql-orm = { path = "../../../../", default-features = false, features = [
  "sqlite",
  "auth-agql",
  "resolver-case-pascal",
  "argument-case-pascal",
  "field-case-pascal",
] }
serde = { version = "1", features = ["derive"] }
