#[cfg(feature = "mssql")]
use super::MssqlBackend;
#[cfg(feature = "postgres")]
use super::PostgresBackend;
#[cfg(feature = "sqlite")]
use super::SqliteBackend;
use super::core::{
    ColumnDef, DbAuthContext, EntityMetadata, IndexDef, RelationMetadata, SchemaPolicy,
    SearchIndexDef, SqlValue,
};
use super::dialect::{DatabaseBackend, SqlDialect, current_backend};
use super::{DefaultBackend, OrmBackend, SqlxBackend};
#[cfg(any(feature = "sqlite", feature = "postgres"))]
use super::{MutationContext, MutationLimit, WriteBackend};
use crate::graphql::pagination::{Connection, Edge, PageInfo, encode_cursor};
use std::any::Any;
use std::marker::PhantomData;
use std::sync::Arc;

pub trait DatabaseEntity {
    const TABLE_NAME: &'static str;
    const PLURAL_NAME: &'static str;
    /// Compatibility accessor for the first primary-key column.
    const PRIMARY_KEY: &'static str;
    /// All primary-key columns in declaration order.
    const PRIMARY_KEYS: &'static [&'static str] = &[Self::PRIMARY_KEY];
    const SCHEMA_POLICY: Option<SchemaPolicy> = None;
    const DEFAULT_SORT: &'static str;

    fn column_names() -> &'static [&'static str];
}

pub trait DatabaseSchema {
    fn columns() -> &'static [ColumnDef];
    fn indexes() -> &'static [IndexDef];
    fn composite_unique_indexes() -> &'static [&'static [&'static str]];
    fn check_constraints() -> &'static [super::core::CheckConstraintDef] {
        &[]
    }
}

pub trait EntityRelations {
    fn relation_metadata() -> &'static [RelationMetadata] {
        &[]
    }
}

pub trait DatabaseSearchSchema {
    fn search_index() -> Option<&'static SearchIndexDef> {
        None
    }
}

/// Repository authorization metadata for one persisted field.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RepositoryFieldPolicyDef {
    /// Rust field identifier used by generated projections.
    pub rust_name: &'static str,
    /// Public API/policy field identity after configured naming rules.
    pub api_name: &'static str,
    /// Optional repository read-policy key.
    pub read_policy: Option<&'static str>,
    /// Optional repository write-policy key.
    pub write_policy: Option<&'static str>,
    /// Whether generated diagnostics and debug output must redact the value.
    pub sensitive: bool,
}

pub trait Entity: DatabaseEntity + DatabaseSchema + EntityRelations + DatabaseSearchSchema {
    fn entity_name() -> &'static str;
    fn metadata() -> &'static EntityMetadata;

    /// Persisted field policy metadata used by non-GraphQL repository paths.
    fn repository_field_policies() -> &'static [RepositoryFieldPolicyDef] {
        &[]
    }

    /// Type-erased record used by repository row/field policy callbacks.
    ///
    /// The source-compatible default supplies no record. Generated
    /// repository-only entities override it; callers then fail closed if an
    /// application row policy requires a record from a third-party entity that
    /// has not opted into this capability.
    fn repository_policy_record(&self) -> Option<&(dyn Any + Send + Sync)> {
        None
    }

    /// Authorize fields supplied by a generated repository create input.
    #[cfg(any(feature = "sqlite", feature = "postgres"))]
    fn authorize_repository_create_fields<'a, B: OrmBackend>(
        _db: &'a crate::db::Database<B>,
        _input: &'a (dyn Any + Send + Sync),
    ) -> futures::future::BoxFuture<'a, crate::Result<()>> {
        Box::pin(async { Ok(()) })
    }

    /// Authorize fields supplied by a generated repository update input.
    #[cfg(any(feature = "sqlite", feature = "postgres"))]
    fn authorize_repository_update_fields<'a, B: OrmBackend>(
        _db: &'a crate::db::Database<B>,
        _existing: Option<&'a (dyn Any + Send + Sync)>,
        _input: &'a (dyn Any + Send + Sync),
    ) -> futures::future::BoxFuture<'a, crate::Result<()>> {
        Box::pin(async { Ok(()) })
    }
}

/// Optional generated PostgreSQL row-level security metadata for an entity.
///
/// Entities without `#[graphql_rls]` use the default `None` implementation and
/// keep existing schema-management behavior.
pub trait DatabaseRls {
    /// Return generated RLS metadata for this entity, when configured.
    fn rls_metadata() -> Option<&'static super::core::RlsEntityMetadata> {
        None
    }
}

pub trait FromSqlRow<B: OrmBackend = DefaultBackend>: Sized {
    fn from_row(row: &B::Row) -> crate::Result<Self>;
}

/// A macro-generated, repository-only typed subset of one managed entity.
///
/// Implementations are generated by `#[graphql_orm(projection(...))]`. The
/// projection DTO is decoded directly from a `SELECT` containing only
/// [`Self::COLUMNS`]; the full entity is never materialized.
pub trait ReadProjection<B: OrmBackend = DefaultBackend>:
    FromSqlRow<B> + Clone + Send + Sync + 'static
{
    type Entity: Entity;
    type Filter: DatabaseFilter + Clone + Send + Sync + 'static;
    type Order: DatabaseOrderBy;

    const COLUMNS: &'static [&'static str];
    /// Rust field identities selected by this projection, in decode order.
    const FIELD_NAMES: &'static [&'static str] = &[];
    #[doc(hidden)]
    const UNIQUE_COLUMNS: &'static [&'static str];
}

pub trait DatabaseFilter {
    fn to_sql_conditions(&self) -> (Vec<String>, Vec<SqlValue>);
    fn is_empty(&self) -> bool;

    /// Return true when at least one predicate must be evaluated against decoded
    /// Rust entities instead of being rendered entirely into SQL.
    fn requires_in_memory_filtering(&self, _backend: DatabaseBackend) -> bool {
        false
    }

    /// Return SQL predicates that are safe to apply before a residual in-memory
    /// matcher runs.
    ///
    /// Generated filters override this for backends such as SQLite spatial
    /// fallback, where ordinary field predicates can still shrink the candidate
    /// set before exact topology checks run in Rust.
    fn to_sql_prefilter_conditions(
        &self,
        backend: DatabaseBackend,
    ) -> (Vec<String>, Vec<SqlValue>) {
        if self.requires_in_memory_filtering(backend) {
            (Vec::new(), Vec::new())
        } else {
            self.to_sql_conditions()
        }
    }

    fn matches_entity(&self, _entity: &(dyn Any + Send + Sync)) -> crate::Result<bool> {
        Ok(true)
    }

    fn to_filter_expression(&self) -> Option<FilterExpression> {
        let (conditions, values) = self.to_sql_conditions();
        filter_expression_from_raw_parts(&conditions, &values)
    }
}

pub trait DatabaseOrderBy {
    fn to_sql_order(&self) -> Option<String>;

    fn to_sort_expression(&self) -> Option<SortExpression> {
        self.to_sql_order().map(|clause| SortExpression { clause })
    }
}

/// Backend-neutral, policy-aware query builder for macro-generated repository entities.
///
/// Unlike the legacy pool-bound compatibility builders, this type is bound to a
/// [`Database`](crate::db::Database), applies configured entity and row policy
/// decisions on the repository surface, and resolves the runtime page bound
/// before executing SQL.
pub struct RepositoryQuery<'a, T, F, O, B: OrmBackend = DefaultBackend> {
    db: &'a crate::db::Database<B>,
    auth: Option<DbAuthContext>,
    query: EntityQuery<T, B>,
    _inputs: PhantomData<(F, O)>,
}

impl<'a, T, F, O, B> RepositoryQuery<'a, T, F, O, B>
where
    B: OrmBackend,
    T: Entity + FromSqlRow<B> + Clone + Send + Sync + 'static,
    F: DatabaseFilter + Clone + Send + Sync + 'static,
    O: DatabaseOrderBy,
{
    /// Create a bounded repository query associated with `db`.
    pub fn new(db: &'a crate::db::Database<B>) -> Self {
        let resolved = db.pagination_config().resolve_page(None, true);
        let query = EntityQuery::new().paginate(&PageInput {
            limit: resolved.limit,
            offset: Some(resolved.offset),
        });
        Self {
            db,
            auth: None,
            query,
            _inputs: PhantomData,
        }
    }

    /// Apply backend-neutral transaction-style database authorization to this read.
    pub fn with_auth(mut self, auth: Option<&DbAuthContext>) -> Self {
        self.auth = auth.cloned();
        self
    }

    /// Apply one generated typed filter.
    pub fn filter(mut self, filter: F) -> Self {
        self.query = self.query.filter_with_entity_matching(&filter);
        self
    }

    /// Add one generated deterministic ordering input.
    pub fn order_by(mut self, order: O) -> Self {
        self.query = self.query.order_by(&order);
        self
    }

    /// Apply the entity's declared default ordering.
    pub fn default_order(mut self) -> Self {
        self.query = self.query.default_order();
        self
    }

    /// Set a requested limit. The database's maximum page limit is applied before SQL execution.
    pub fn limit(mut self, limit: i64) -> Self {
        let limit = self
            .db
            .pagination_config()
            .clamp_explicit_limit(Some(limit));
        let offset = self.query.page.as_ref().and_then(|page| page.offset);
        self.query = self.query.paginate(&PageInput { limit, offset });
        self
    }

    /// Set a non-negative offset while retaining the configured bound.
    pub fn offset(mut self, offset: i64) -> Self {
        let limit = self.query.page.as_ref().and_then(|page| page.limit);
        self.query = self.query.paginate(&PageInput {
            limit,
            offset: Some(offset.max(0)),
        });
        self
    }

    async fn authorize(self) -> crate::Result<(Self, &'static EntityMetadata)> {
        let metadata = T::metadata();
        self.db
            .ensure_entity_access(
                None,
                metadata.entity_name,
                metadata.read_policy,
                super::core::EntityAccessKind::Read,
                super::core::EntityAccessSurface::Repository,
            )
            .await
            .map_err(crate::graphql::errors::sqlx_error_from_graphql)?;
        Ok((self, metadata))
    }

    async fn fetch_visible(
        self,
        pagination_override: Option<PaginationConfig>,
    ) -> crate::Result<Vec<T>> {
        let (this, metadata) = self.authorize().await?;
        let rows = if let Some(pagination) = pagination_override {
            this.query
                .fetch_all_with_auth_and_pagination(this.db, this.auth.as_ref(), pagination)
                .await?
        } else {
            this.query
                .fetch_all_with_auth(this.db, this.auth.as_ref())
                .await?
        };
        let mut visible = Vec::with_capacity(rows.len());
        for row in rows {
            if this
                .db
                .can_read_row(
                    None,
                    metadata.entity_name,
                    metadata.read_policy,
                    super::core::EntityAccessSurface::Repository,
                    &row as &(dyn Any + Send + Sync),
                )
                .await
                .map_err(crate::graphql::errors::sqlx_error_from_graphql)?
            {
                for field in T::repository_field_policies() {
                    this.db
                        .ensure_repository_readable_field(
                            None,
                            metadata.entity_name,
                            field.api_name,
                            field.read_policy,
                            Some(&row as &(dyn Any + Send + Sync)),
                        )
                        .await
                        .map_err(crate::graphql::errors::sqlx_error_from_public)?;
                }
                visible.push(row);
            }
        }
        Ok(visible)
    }

    /// Fetch all visible rows within the resolved bound.
    ///
    /// # Errors
    ///
    /// Returns a safe authorization, query-rendering, backend, or row-decoding
    /// error. Declared policies without the required provider fail closed.
    pub async fn fetch_all(self) -> crate::Result<Vec<T>> {
        self.fetch_visible(None).await
    }

    /// Fetch the first visible row within the resolved bound.
    ///
    /// # Errors
    ///
    /// Returns the same safe errors as [`Self::fetch_all`].
    pub async fn fetch_first(self) -> crate::Result<Option<T>> {
        Ok(self.fetch_all().await?.into_iter().next())
    }

    /// Fetch zero or one visible row, failing closed if more than one row is visible.
    ///
    /// # Errors
    ///
    /// Returns a cardinality error for multiple visible rows, or the same safe
    /// errors as [`Self::fetch_all`].
    pub async fn fetch_optional_one(mut self) -> crate::Result<Option<T>> {
        // Cardinality checks always use one bounded look-ahead row. This must not
        // be clamped to a configured maximum of one, or a second matching row
        // could be mistaken for a unique result.
        let offset = self.query.page.as_ref().and_then(|page| page.offset);
        self.query = self.query.paginate(&PageInput {
            limit: Some(2),
            offset,
        });
        let rows = self
            .fetch_visible(Some(PaginationConfig::unbounded()))
            .await?;
        if rows.len() > 1 {
            return Err(sqlx::Error::Protocol(
                "repository optional-one query matched more than one row".to_string(),
            ));
        }
        Ok(rows.into_iter().next())
    }
}

/// SQL filter expression tree used by generated and host-authored queries.
///
/// Prefer typed filter inputs and [`FilterExpression::trusted_fragment`] for
/// host-owned predicates. [`FilterExpression::Raw`] remains for generated
/// compatibility but is a deliberate trusted-SQL surface: never pass
/// unvalidated user input as the clause text.
#[derive(Clone, Debug, PartialEq)]
pub enum FilterExpression {
    /// Legacy trusted raw fragment.
    ///
    /// Prefer [`Self::TrustedFragment`]. The clause must be host- or
    /// macro-generated SQL with placeholders only; values are bound parameters.
    Raw {
        clause: String,
        values: Vec<SqlValue>,
    },
    /// Explicit trusted SQL fragment constructed by host or ORM internals.
    ///
    /// Construction is deliberate: callers must not interpolate user input into
    /// `clause`. Bind all values through `values`.
    TrustedFragment {
        clause: String,
        values: Vec<SqlValue>,
    },
    /// Logical conjunction of child filters.
    And(Vec<FilterExpression>),
    /// Logical disjunction of child filters.
    Or(Vec<FilterExpression>),
}

impl FilterExpression {
    /// Construct an explicitly trusted parameterized SQL fragment.
    ///
    /// # Safety contract
    ///
    /// `clause` must not contain unvalidated user input. Identifiers must be
    /// validated/quoted by the caller or dialect helpers before construction.
    pub fn trusted_fragment(clause: impl Into<String>, values: Vec<SqlValue>) -> Self {
        Self::TrustedFragment {
            clause: clause.into(),
            values,
        }
    }

    /// Compatibility constructor for generated raw fragments.
    #[doc(hidden)]
    pub fn raw(clause: impl Into<String>, values: Vec<SqlValue>) -> Self {
        Self::Raw {
            clause: clause.into(),
            values,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct SortExpression {
    pub clause: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RenderedQuery {
    pub sql: String,
    pub values: Vec<SqlValue>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SelectQuery {
    pub table: &'static str,
    pub columns: Vec<String>,
    pub filter: Option<FilterExpression>,
    pub sorts: Vec<SortExpression>,
    pub pagination: Option<PaginationRequest>,
    pub count_only: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AggregateFunction {
    Count,
    Max,
    Min,
}

impl AggregateFunction {
    pub fn as_sql(self) -> &'static str {
        match self {
            Self::Count => "COUNT",
            Self::Max => "MAX",
            Self::Min => "MIN",
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct AggregateQuery {
    pub table: &'static str,
    pub function: AggregateFunction,
    pub column: Option<String>,
    pub filter: Option<FilterExpression>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DeleteQuery {
    pub table: &'static str,
    pub filter: Option<FilterExpression>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PaginationConfig {
    /// Limit applied to connection-style queries when the request omits a limit.
    pub default_limit: Option<i64>,
    /// Maximum accepted explicit or default limit.
    pub max_limit: Option<i64>,
}

impl Default for PaginationConfig {
    fn default() -> Self {
        Self {
            default_limit: Some(Self::DEFAULT_LIMIT),
            max_limit: Some(Self::DEFAULT_MAX_LIMIT),
        }
    }
}

impl PaginationConfig {
    /// Secure recommended default connection limit.
    pub const SECURE_DEFAULT_LIMIT: i64 = 50;
    /// Secure recommended maximum connection limit.
    pub const SECURE_MAX_LIMIT: i64 = 100;
    /// Legacy default connection limit retained for migration.
    pub const LEGACY_DEFAULT_LIMIT: i64 = 1000;
    /// Legacy maximum connection limit retained for migration.
    pub const LEGACY_MAX_LIMIT: i64 = 1000;

    /// Default connection limit used when a request omits `PageInput.limit`.
    ///
    /// **Current default:** [`Self::SECURE_DEFAULT_LIMIT`] (`50`).
    /// **Previous default:** [`Self::LEGACY_DEFAULT_LIMIT`] (`1000`).
    /// **Secure recommended:** [`Self::SECURE_DEFAULT_LIMIT`].
    /// Use [`Self::legacy`] to restore the previous behavior during migration.
    pub const DEFAULT_LIMIT: i64 = Self::SECURE_DEFAULT_LIMIT;
    /// Default cap applied to explicit and default limits.
    ///
    /// **Current default:** [`Self::SECURE_MAX_LIMIT`] (`100`).
    /// **Previous default:** [`Self::LEGACY_MAX_LIMIT`] (`1000`).
    pub const DEFAULT_MAX_LIMIT: i64 = Self::SECURE_MAX_LIMIT;

    /// Create a config that does not add a default limit and does not cap limits.
    ///
    /// Use only for trusted internal jobs. GraphQL surfaces should keep bounds.
    pub const fn unbounded() -> Self {
        Self {
            default_limit: None,
            max_limit: None,
        }
    }

    /// Restore the pre-0.3 connection limits (`1000` / `1000`).
    pub const fn legacy() -> Self {
        Self {
            default_limit: Some(Self::LEGACY_DEFAULT_LIMIT),
            max_limit: Some(Self::LEGACY_MAX_LIMIT),
        }
    }

    /// Secure recommended limits (`50` / `100`).
    pub const fn secure() -> Self {
        Self {
            default_limit: Some(Self::SECURE_DEFAULT_LIMIT),
            max_limit: Some(Self::SECURE_MAX_LIMIT),
        }
    }

    /// Create a config with the default limit disabled but explicit limits capped.
    pub const fn explicit_only(max_limit: i64) -> Self {
        Self {
            default_limit: None,
            max_limit: Some(max_limit),
        }
    }

    /// Return a copy with a different default limit.
    pub fn with_default_limit(mut self, default_limit: Option<i64>) -> Self {
        self.default_limit = default_limit;
        self
    }

    /// Return a copy with a different maximum limit.
    pub fn with_max_limit(mut self, max_limit: Option<i64>) -> Self {
        self.max_limit = max_limit;
        self
    }

    /// Clamp one explicit limit without applying a default.
    pub fn clamp_explicit_limit(&self, limit: Option<i64>) -> Option<i64> {
        limit.map(|limit| self.clamp_limit_value(limit))
    }

    /// Resolve an optional page input into an offset/limit pair.
    ///
    /// When `apply_default_limit` is true, `default_limit` is used if the page
    /// input or its `limit` field is absent. Repository-style `fetch_all` paths
    /// pass false so callers can intentionally fetch all rows.
    pub fn resolve_page(
        &self,
        page: Option<&PageInput>,
        apply_default_limit: bool,
    ) -> PaginationRequest {
        let offset = page.map(PageInput::offset).unwrap_or(0);
        let requested_limit = page.and_then(|page| page.limit);
        let limit = if requested_limit.is_some() {
            self.clamp_explicit_limit(requested_limit)
        } else if apply_default_limit {
            self.clamp_explicit_limit(self.default_limit)
        } else {
            None
        };
        PaginationRequest { limit, offset }
    }

    fn clamp_limit_value(&self, limit: i64) -> i64 {
        let normalized = limit.max(0);
        match self.max_limit {
            Some(max_limit) => normalized.min(max_limit.max(0)),
            None => normalized,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct PaginationRequest {
    pub limit: Option<i64>,
    pub offset: i64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SchemaLimits {
    /// Maximum GraphQL query depth applied by generated `schema_builder` helpers.
    pub max_depth: Option<usize>,
    /// Maximum GraphQL query complexity applied by generated `schema_builder` helpers.
    pub max_complexity: Option<usize>,
}

impl Default for SchemaLimits {
    fn default() -> Self {
        Self {
            max_depth: Some(Self::DEFAULT_MAX_DEPTH),
            max_complexity: Some(Self::DEFAULT_MAX_COMPLEXITY),
        }
    }
}

impl SchemaLimits {
    /// Default GraphQL query depth cap for generated schemas.
    pub const DEFAULT_MAX_DEPTH: usize = 16;
    /// Default GraphQL query complexity cap for generated schemas.
    pub const DEFAULT_MAX_COMPLEXITY: usize = 20_000;

    /// Create limits with both depth and complexity checks disabled.
    pub const fn unbounded() -> Self {
        Self {
            max_depth: None,
            max_complexity: None,
        }
    }

    /// Return a copy with a different depth cap.
    pub const fn with_max_depth(mut self, max_depth: Option<usize>) -> Self {
        self.max_depth = max_depth;
        self
    }

    /// Return a copy with a different complexity cap.
    pub const fn with_max_complexity(mut self, max_complexity: Option<usize>) -> Self {
        self.max_complexity = max_complexity;
        self
    }

    /// Apply these limits to an async-graphql schema builder.
    pub fn apply<Query, Mutation, Subscription>(
        self,
        mut builder: async_graphql::SchemaBuilder<Query, Mutation, Subscription>,
    ) -> async_graphql::SchemaBuilder<Query, Mutation, Subscription> {
        if let Some(max_depth) = self.max_depth {
            builder = builder.limit_depth(max_depth);
        }
        if let Some(max_complexity) = self.max_complexity {
            builder = builder.limit_complexity(max_complexity);
        }
        builder
    }
}

impl From<&PageInput> for PaginationRequest {
    fn from(value: &PageInput) -> Self {
        PaginationConfig::default().resolve_page(Some(value), false)
    }
}

#[derive(async_graphql::Enum, Copy, Clone, Debug, Eq, PartialEq)]
pub enum OrderDirection {
    Asc,
    Desc,
}

impl OrderDirection {
    pub fn to_sql(self) -> &'static str {
        match self {
            Self::Asc => "ASC",
            Self::Desc => "DESC",
        }
    }
}

impl DatabaseFilter for () {
    fn to_sql_conditions(&self) -> (Vec<String>, Vec<SqlValue>) {
        (Vec::new(), Vec::new())
    }

    fn is_empty(&self) -> bool {
        true
    }
}

impl DatabaseOrderBy for () {
    fn to_sql_order(&self) -> Option<String> {
        None
    }
}

#[derive(
    async_graphql::Enum, serde::Serialize, serde::Deserialize, Copy, Clone, Debug, Eq, PartialEq,
)]
pub enum ChangeAction {
    Created,
    Updated,
    Deleted,
}

#[derive(
    async_graphql::Enum, serde::Serialize, serde::Deserialize, Copy, Clone, Debug, Eq, PartialEq,
)]
pub enum ChangeKind {
    Direct,
    Propagated,
}

#[derive(async_graphql::InputObject, Clone, Debug, Default)]
#[cfg_attr(feature = "field-case-pascal", graphql(rename_fields = "PascalCase"))]
#[cfg_attr(feature = "field-case-snake", graphql(rename_fields = "snake_case"))]
#[cfg_attr(
    feature = "field-case-screaming-snake",
    graphql(rename_fields = "SCREAMING_SNAKE_CASE")
)]
#[cfg_attr(feature = "field-case-lower", graphql(rename_fields = "lowercase"))]
#[cfg_attr(feature = "field-case-upper", graphql(rename_fields = "UPPERCASE"))]
pub struct SubscriptionFilterInput {
    pub actions: Option<Vec<ChangeAction>>,
    pub dummy: Option<bool>,
}

#[derive(async_graphql::InputObject, Clone, Debug, Default)]
#[cfg_attr(feature = "field-case-pascal", graphql(rename_fields = "PascalCase"))]
#[cfg_attr(feature = "field-case-snake", graphql(rename_fields = "snake_case"))]
#[cfg_attr(
    feature = "field-case-screaming-snake",
    graphql(rename_fields = "SCREAMING_SNAKE_CASE")
)]
#[cfg_attr(feature = "field-case-lower", graphql(rename_fields = "lowercase"))]
#[cfg_attr(feature = "field-case-upper", graphql(rename_fields = "UPPERCASE"))]
/// Offset pagination input shared by generated list, relation, and search APIs.
///
/// Generated connection resolvers combine this request input with
/// [`PaginationConfig`] from the runtime `Database`. The default config applies
/// a limit of [`PaginationConfig::DEFAULT_LIMIT`] (`50`) when this input or its
/// `limit` field is omitted, and clamps explicit limits to
/// [`PaginationConfig::DEFAULT_MAX_LIMIT`] (`100`). Use
/// [`PaginationConfig::legacy`] on `Database` for the previous 1000/1000 caps
/// during migration.
pub struct PageInput {
    /// Requested page size. Explicit limits are clamped by the runtime
    /// [`PaginationConfig`] before SQL rendering.
    pub limit: Option<i64>,
    /// Requested offset. Negative offsets are treated as `0`.
    pub offset: Option<i64>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KeysetDirection {
    Asc,
    Desc,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KeysetNulls {
    First,
    Last,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct KeysetOrderColumn {
    pub column: &'static str,
    pub direction: KeysetDirection,
    pub nulls: KeysetNulls,
}

impl KeysetOrderColumn {
    pub const fn asc(column: &'static str) -> Self {
        Self {
            column,
            direction: KeysetDirection::Asc,
            nulls: KeysetNulls::Last,
        }
    }

    pub const fn desc(column: &'static str) -> Self {
        Self {
            column,
            direction: KeysetDirection::Desc,
            nulls: KeysetNulls::Last,
        }
    }

    pub const fn nulls_first(mut self) -> Self {
        self.nulls = KeysetNulls::First;
        self
    }

    /// Reverses direction and null placement for a backward database read.
    pub const fn reversed(mut self) -> Self {
        self.direction = match self.direction {
            KeysetDirection::Asc => KeysetDirection::Desc,
            KeysetDirection::Desc => KeysetDirection::Asc,
        };
        self.nulls = match self.nulls {
            KeysetNulls::First => KeysetNulls::Last,
            KeysetNulls::Last => KeysetNulls::First,
        };
        self
    }

    pub fn order_sql(self) -> String {
        let direction = match self.direction {
            KeysetDirection::Asc => "ASC",
            KeysetDirection::Desc => "DESC",
        };
        let null_rank = match self.nulls {
            KeysetNulls::First => 0,
            KeysetNulls::Last => 1,
        };
        let nonnull_rank = 1 - null_rank;
        format!(
            "CASE WHEN {} IS NULL THEN {} ELSE {} END ASC, {} {}",
            self.column, null_rank, nonnull_rank, self.column, direction
        )
    }
}

fn keyset_sql_value(value: &crate::graphql::pagination::KeysetValue) -> Option<SqlValue> {
    use crate::graphql::pagination::KeysetValue;
    match value {
        KeysetValue::Null => None,
        KeysetValue::String(value) => Some(SqlValue::String(value.clone())),
        KeysetValue::Int(value) => Some(SqlValue::Int(*value)),
        KeysetValue::Float(value) => Some(SqlValue::Float(*value)),
        KeysetValue::Bool(value) => Some(SqlValue::Bool(*value)),
        KeysetValue::Uuid(value) => uuid::Uuid::parse_str(value).ok().map(SqlValue::Uuid),
        KeysetValue::Bytes(value) => Some(SqlValue::Bytes(value.clone())),
    }
}

/// Render the lexicographic `after` predicate with explicit nullable ordering.
pub fn render_keyset_after(
    backend: DatabaseBackend,
    columns: &[KeysetOrderColumn],
    cursor: &[crate::graphql::pagination::KeysetValue],
    start_index: usize,
) -> Result<(String, Vec<SqlValue>), crate::graphql::errors::OrmPublicError> {
    use crate::graphql::errors::{OrmErrorCode, OrmPublicError};
    use crate::graphql::pagination::KeysetValue;
    if columns.len() != cursor.len() || columns.is_empty() {
        return Err(OrmPublicError::new(OrmErrorCode::CursorInvalid));
    }
    let mut branches = Vec::new();
    let mut values = Vec::new();
    for index in 0..columns.len() {
        let mut terms = Vec::new();
        for prior in 0..index {
            let column = columns[prior];
            match &cursor[prior] {
                KeysetValue::Null => terms.push(format!("{} IS NULL", column.column)),
                value => {
                    let value = keyset_sql_value(value)
                        .ok_or_else(|| OrmPublicError::new(OrmErrorCode::CursorInvalid))?;
                    terms.push(format!(
                        "{} = {}",
                        column.column,
                        backend.placeholder(start_index + values.len())
                    ));
                    values.push(value);
                }
            }
        }
        let column = columns[index];
        let comparison = match &cursor[index] {
            KeysetValue::Null => match column.nulls {
                KeysetNulls::First => format!("{} IS NOT NULL", column.column),
                KeysetNulls::Last => "1 = 0".to_string(),
            },
            value => {
                let value = keyset_sql_value(value)
                    .ok_or_else(|| OrmPublicError::new(OrmErrorCode::CursorInvalid))?;
                let operator = match column.direction {
                    KeysetDirection::Asc => ">",
                    KeysetDirection::Desc => "<",
                };
                let scalar = format!(
                    "{} {} {}",
                    column.column,
                    operator,
                    backend.placeholder(start_index + values.len())
                );
                values.push(value);
                match column.nulls {
                    KeysetNulls::First => format!("({} IS NOT NULL AND {scalar})", column.column),
                    KeysetNulls::Last => format!("({} IS NULL OR {scalar})", column.column),
                }
            }
        };
        terms.push(comparison);
        branches.push(format!("({})", terms.join(" AND ")));
    }
    Ok((branches.join(" OR "), values))
}

/// Render the lexicographic `before` predicate with explicit nullable ordering.
pub fn render_keyset_before(
    backend: DatabaseBackend,
    columns: &[KeysetOrderColumn],
    cursor: &[crate::graphql::pagination::KeysetValue],
    start_index: usize,
) -> Result<(String, Vec<SqlValue>), crate::graphql::errors::OrmPublicError> {
    use crate::graphql::errors::{OrmErrorCode, OrmPublicError};
    use crate::graphql::pagination::KeysetValue;
    if columns.len() != cursor.len() || columns.is_empty() {
        return Err(OrmPublicError::new(OrmErrorCode::CursorInvalid));
    }
    let mut branches = Vec::new();
    let mut values = Vec::new();
    for index in 0..columns.len() {
        let mut terms = Vec::new();
        for prior in 0..index {
            let column = columns[prior];
            match &cursor[prior] {
                KeysetValue::Null => terms.push(format!("{} IS NULL", column.column)),
                value => {
                    let value = keyset_sql_value(value)
                        .ok_or_else(|| OrmPublicError::new(OrmErrorCode::CursorInvalid))?;
                    terms.push(format!(
                        "{} = {}",
                        column.column,
                        backend.placeholder(start_index + values.len())
                    ));
                    values.push(value);
                }
            }
        }
        let column = columns[index];
        let comparison = match &cursor[index] {
            KeysetValue::Null => match column.nulls {
                KeysetNulls::First => "1 = 0".to_string(),
                KeysetNulls::Last => format!("{} IS NOT NULL", column.column),
            },
            value => {
                let value = keyset_sql_value(value)
                    .ok_or_else(|| OrmPublicError::new(OrmErrorCode::CursorInvalid))?;
                let operator = match column.direction {
                    KeysetDirection::Asc => "<",
                    KeysetDirection::Desc => ">",
                };
                let scalar = format!(
                    "{} {} {}",
                    column.column,
                    operator,
                    backend.placeholder(start_index + values.len())
                );
                values.push(value);
                match column.nulls {
                    KeysetNulls::First => {
                        format!("({} IS NULL OR {scalar})", column.column)
                    }
                    KeysetNulls::Last => {
                        format!("({} IS NOT NULL AND {scalar})", column.column)
                    }
                }
            }
        };
        terms.push(comparison);
        branches.push(format!("({})", terms.join(" AND ")));
    }

    Ok((format!("({})", branches.join(" OR ")), values))
}

impl PageInput {
    /// Default max limit retained for compatibility with older callers.
    pub const MAX_LIMIT: i64 = PaginationConfig::DEFAULT_MAX_LIMIT;

    /// Return a non-negative offset for SQL rendering and in-memory slicing.
    pub fn offset(&self) -> i64 {
        self.offset.unwrap_or(0).max(0)
    }

    /// Return the explicit requested limit clamped by the default pagination
    /// config. This does not apply the default connection limit when the field
    /// is omitted.
    ///
    /// This compatibility helper cannot observe a `Database` handle's custom
    /// pagination configuration. Use [`Self::limit_with_config`] or
    /// [`PaginationConfig::resolve_page`] for application code that supports
    /// configured caps.
    #[deprecated(
        since = "0.2.17",
        note = "use PageInput::limit_with_config or PaginationConfig::resolve_page"
    )]
    pub fn limit(&self) -> Option<i64> {
        PaginationConfig::default().clamp_explicit_limit(self.limit)
    }

    /// Resolve this input with a caller-provided pagination config.
    pub fn limit_with_config(&self, config: PaginationConfig) -> Option<i64> {
        config.clamp_explicit_limit(self.limit)
    }
}

pub trait PoolProvider<B: OrmBackend = DefaultBackend> {
    fn pool(&self) -> &B::Pool;

    fn pagination_config(&self) -> PaginationConfig {
        PaginationConfig::default()
    }
}

pub trait DatabaseExecutor<B: OrmBackend = DefaultBackend>: PoolProvider<B> {
    fn backend(&self) -> DatabaseBackend {
        B::DIALECT
    }
}

#[cfg(feature = "sqlite")]
impl PoolProvider<SqliteBackend> for sqlx::SqlitePool {
    fn pool(&self) -> &<SqliteBackend as OrmBackend>::Pool {
        self
    }
}

#[cfg(feature = "sqlite")]
impl DatabaseExecutor<SqliteBackend> for sqlx::SqlitePool {}

#[cfg(feature = "postgres")]
impl PoolProvider<PostgresBackend> for sqlx::PgPool {
    fn pool(&self) -> &<PostgresBackend as OrmBackend>::Pool {
        self
    }
}

#[cfg(feature = "postgres")]
impl DatabaseExecutor<PostgresBackend> for sqlx::PgPool {}

#[cfg(feature = "mssql")]
impl PoolProvider<MssqlBackend> for crate::db::mssql::MssqlPool {
    fn pool(&self) -> &<MssqlBackend as OrmBackend>::Pool {
        self
    }
}

#[cfg(feature = "mssql")]
impl DatabaseExecutor<MssqlBackend> for crate::db::mssql::MssqlPool {}

impl<B: OrmBackend> PoolProvider<B> for crate::db::Database<B> {
    fn pool(&self) -> &B::Pool {
        self.pool()
    }

    fn pagination_config(&self) -> PaginationConfig {
        crate::db::Database::pagination_config(self)
    }
}

impl<B: OrmBackend> DatabaseExecutor<B> for crate::db::Database<B> {}

#[allow(async_fn_in_trait)]
pub trait RelationLoader<B: OrmBackend = DefaultBackend> {
    async fn load_relations(
        &mut self,
        pool: &B::Pool,
        selection: &[async_graphql::context::SelectionField<'_>],
    ) -> crate::Result<()>;

    async fn bulk_load_relations(
        entities: &mut [Self],
        pool: &B::Pool,
        selection: &[async_graphql::context::SelectionField<'_>],
    ) -> crate::Result<()>
    where
        Self: Sized;

    async fn load_relations_with_auth(
        &mut self,
        pool: &B::Pool,
        selection: &[async_graphql::context::SelectionField<'_>],
        _auth: Option<&DbAuthContext>,
    ) -> crate::Result<()> {
        self.load_relations(pool, selection).await
    }

    async fn bulk_load_relations_with_auth(
        entities: &mut [Self],
        pool: &B::Pool,
        selection: &[async_graphql::context::SelectionField<'_>],
        _auth: Option<&DbAuthContext>,
    ) -> crate::Result<()>
    where
        Self: Sized,
    {
        Self::bulk_load_relations(entities, pool, selection).await
    }
}

/// Small deterministic substring scorer used by fallback query paths.
pub struct FuzzyMatcher {
    query: String,
    threshold: f64,
}

#[derive(Clone, Debug)]
pub struct MatchResult<T> {
    pub entity: T,
    pub score: f64,
}

impl FuzzyMatcher {
    pub fn new(query: &str) -> Self {
        Self {
            query: query.to_lowercase(),
            threshold: 0.0,
        }
    }

    pub fn with_threshold(mut self, threshold: f64) -> Self {
        self.threshold = threshold;
        self
    }

    pub fn filter_and_score<T, F>(&self, items: Vec<T>, extract: F) -> Vec<MatchResult<T>>
    where
        F: Fn(&T) -> Option<&str>,
    {
        let mut out = Vec::new();
        for item in items {
            let score = extract(&item)
                .map(|candidate| {
                    if candidate.to_lowercase().contains(&self.query) {
                        1.0
                    } else {
                        0.0
                    }
                })
                .unwrap_or(0.0);

            if score >= self.threshold {
                out.push(MatchResult {
                    entity: item,
                    score,
                });
            }
        }
        out
    }
}

/// Escape `%`, `_`, and `\` in a user string before binding it to a SQL
/// `LIKE`/`ILIKE` predicate that uses `ESCAPE '\'`.
pub fn escape_like_pattern(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' | '%' | '_' => {
                escaped.push('\\');
                escaped.push(ch);
            }
            _ => escaped.push(ch),
        }
    }
    escaped
}

/// Build an escaped contains pattern for SQL `LIKE`/`ILIKE`.
pub fn contains_like_pattern(value: &str) -> String {
    format!("%{}%", escape_like_pattern(value))
}

/// Build an escaped starts-with pattern for SQL `LIKE`/`ILIKE`.
pub fn starts_with_like_pattern(value: &str) -> String {
    format!("{}%", escape_like_pattern(value))
}

/// Build an escaped ends-with pattern for SQL `LIKE`/`ILIKE`.
pub fn ends_with_like_pattern(value: &str) -> String {
    format!("%{}", escape_like_pattern(value))
}

pub fn generate_candidate_pattern(value: &str) -> String {
    contains_like_pattern(value)
}

fn filter_expression_from_raw_parts(
    conditions: &[String],
    values: &[SqlValue],
) -> Option<FilterExpression> {
    if conditions.is_empty() {
        return None;
    }

    let mut value_iter = values.iter().cloned();
    let filters = conditions
        .iter()
        .map(|clause| {
            let placeholder_count = count_placeholders(clause);
            let clause_values = value_iter
                .by_ref()
                .take(placeholder_count)
                .collect::<Vec<_>>();
            FilterExpression::Raw {
                clause: clause.clone(),
                values: clause_values,
            }
        })
        .collect::<Vec<_>>();

    if filters.len() == 1 {
        filters.into_iter().next()
    } else {
        Some(FilterExpression::And(filters))
    }
}

pub fn count_placeholders(clause: &str) -> usize {
    let chars: Vec<char> = clause.chars().collect();
    let mut count = 0usize;
    let mut i = 0usize;
    let mut in_single_quote = false;
    let mut in_double_quote = false;
    let mut in_bracket_quote = false;
    while i < chars.len() {
        let ch = chars[i];
        if in_single_quote {
            if ch == '\'' {
                if i + 1 < chars.len() && chars[i + 1] == '\'' {
                    i += 2;
                    continue;
                }
                in_single_quote = false;
            }
            i += 1;
            continue;
        }
        if in_double_quote {
            if ch == '"' {
                if i + 1 < chars.len() && chars[i + 1] == '"' {
                    i += 2;
                    continue;
                }
                in_double_quote = false;
            }
            i += 1;
            continue;
        }
        if in_bracket_quote {
            if ch == ']' {
                if i + 1 < chars.len() && chars[i + 1] == ']' {
                    i += 2;
                    continue;
                }
                in_bracket_quote = false;
            }
            i += 1;
            continue;
        }
        match ch {
            '\'' => {
                in_single_quote = true;
                i += 1;
            }
            '"' => {
                in_double_quote = true;
                i += 1;
            }
            '[' => {
                in_bracket_quote = true;
                i += 1;
            }
            '?' => {
                count += 1;
                i += 1;
            }
            '$' => {
                let mut j = i + 1;
                let mut saw_digit = false;
                while j < chars.len() && chars[j].is_ascii_digit() {
                    saw_digit = true;
                    j += 1;
                }
                if saw_digit {
                    count += 1;
                    i = j;
                } else {
                    i += 1;
                }
            }
            '@' if i + 1 < chars.len() && chars[i + 1].eq_ignore_ascii_case(&'p') => {
                let mut j = i + 2;
                let mut saw_digit = false;
                while j < chars.len() && chars[j].is_ascii_digit() {
                    saw_digit = true;
                    j += 1;
                }
                if saw_digit {
                    count += 1;
                    i = j;
                } else {
                    i += 1;
                }
            }
            _ => i += 1,
        }
    }
    count
}

pub fn render_filter_expression(
    dialect: DatabaseBackend,
    filter: &FilterExpression,
    next_index: &mut usize,
    bind_values: &mut Vec<SqlValue>,
) -> String {
    match filter {
        FilterExpression::Raw { clause, values }
        | FilterExpression::TrustedFragment { clause, values } => {
            let rendered = dialect.normalize_sql(clause, *next_index);
            *next_index += values.len();
            bind_values.extend(values.iter().cloned());
            rendered
        }
        FilterExpression::And(filters) => filters
            .iter()
            .map(|filter| render_filter_expression(dialect, filter, next_index, bind_values))
            .filter(|sql| !sql.is_empty())
            .map(|sql| format!("({sql})"))
            .collect::<Vec<_>>()
            .join(" AND "),
        FilterExpression::Or(filters) => filters
            .iter()
            .map(|filter| render_filter_expression(dialect, filter, next_index, bind_values))
            .filter(|sql| !sql.is_empty())
            .map(|sql| format!("({sql})"))
            .collect::<Vec<_>>()
            .join(" OR "),
    }
}

pub fn render_select_query(dialect: DatabaseBackend, query: &SelectQuery) -> RenderedQuery {
    let projection = if query.count_only {
        dialect.count_projection().to_string()
    } else {
        query.columns.join(", ")
    };
    let mut sql = format!("SELECT {} FROM {}", projection, query.table);
    let mut values = Vec::new();
    let mut next_index = 1usize;

    if let Some(filter) = &query.filter {
        let where_sql = render_filter_expression(dialect, filter, &mut next_index, &mut values);
        if !where_sql.is_empty() {
            sql.push_str(" WHERE ");
            sql.push_str(&where_sql);
        }
    }

    if !query.count_only && !query.sorts.is_empty() {
        sql.push_str(" ORDER BY ");
        sql.push_str(
            &query
                .sorts
                .iter()
                .map(|sort| sort.clause.clone())
                .collect::<Vec<_>>()
                .join(", "),
        );
    }

    if !query.count_only {
        if let Some(page) = &query.pagination {
            if dialect == DatabaseBackend::Mssql && query.sorts.is_empty() {
                sql.push_str(" ORDER BY (SELECT 1)");
            }
            sql.push_str(&dialect.render_pagination(page.limit, page.offset));
        }
    }

    RenderedQuery { sql, values }
}

pub fn render_aggregate_query(dialect: DatabaseBackend, query: &AggregateQuery) -> RenderedQuery {
    let argument = query.column.as_deref().unwrap_or("*");
    let projection = format!(
        "{}({}) AS __gom_aggregate",
        query.function.as_sql(),
        argument
    );
    let mut sql = format!("SELECT {} FROM {}", projection, query.table);
    let mut values = Vec::new();
    let mut next_index = 1usize;

    if let Some(filter) = &query.filter {
        let where_sql = render_filter_expression(dialect, filter, &mut next_index, &mut values);
        if !where_sql.is_empty() {
            sql.push_str(" WHERE ");
            sql.push_str(&where_sql);
        }
    }

    RenderedQuery { sql, values }
}

pub fn render_delete_query(dialect: DatabaseBackend, query: &DeleteQuery) -> RenderedQuery {
    let mut sql = format!("DELETE FROM {}", query.table);
    let mut values = Vec::new();
    let mut next_index = 1usize;

    if let Some(filter) = &query.filter {
        let where_sql = render_filter_expression(dialect, filter, &mut next_index, &mut values);
        if !where_sql.is_empty() {
            sql.push_str(" WHERE ");
            sql.push_str(&where_sql);
        }
    }

    RenderedQuery { sql, values }
}

pub fn render_upsert_sql(
    dialect: DatabaseBackend,
    table: &str,
    insert_columns: &[&str],
    insert_values: &[&str],
    conflict_columns: &[&str],
    update_columns: &[&str],
    update_updated_at: bool,
) -> String {
    let quoted_table = dialect.quote_identifier_path(table);
    let quoted_insert_columns = insert_columns
        .iter()
        .map(|column| dialect.quote_identifier_path(column))
        .collect::<Vec<_>>();
    let quoted_conflict_columns = conflict_columns
        .iter()
        .map(|column| dialect.quote_identifier_path(column))
        .collect::<Vec<_>>();
    let mut set_clauses = update_columns
        .iter()
        .map(|column| {
            let quoted = dialect.quote_identifier_path(column);
            format!("{quoted} = EXCLUDED.{quoted}")
        })
        .collect::<Vec<_>>();
    if update_updated_at {
        set_clauses.push(format!(
            "{} = {}",
            dialect.quote_identifier("updated_at"),
            dialect.current_epoch_expr()
        ));
    }

    format!(
        "INSERT INTO {} ({}) VALUES ({}) ON CONFLICT ({}) DO UPDATE SET {}",
        quoted_table,
        quoted_insert_columns.join(", "),
        insert_values.join(", "),
        quoted_conflict_columns.join(", "),
        set_clauses.join(", ")
    )
}

/// Render a bound insert that ignores one declared primary/unique conflict.
pub fn render_insert_if_absent_sql(
    dialect: DatabaseBackend,
    table: &str,
    insert_columns: &[&str],
    insert_values: &[&str],
    conflict_columns: &[&str],
) -> String {
    let table = dialect.quote_identifier_path(table);
    let columns = insert_columns
        .iter()
        .map(|column| dialect.quote_identifier_path(column))
        .collect::<Vec<_>>()
        .join(", ");
    let conflicts = conflict_columns
        .iter()
        .map(|column| dialect.quote_identifier_path(column))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "INSERT INTO {table} ({columns}) VALUES ({}) ON CONFLICT ({conflicts}) DO NOTHING",
        insert_values.join(", ")
    )
}

pub fn render_insert_sql(
    dialect: DatabaseBackend,
    table: &str,
    insert_columns: &[&str],
    insert_values: &[&str],
) -> String {
    let table = dialect.quote_identifier_path(table);
    let columns = insert_columns
        .iter()
        .map(|column| dialect.quote_identifier_path(column))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "INSERT INTO {table} ({columns}) VALUES ({})",
        insert_values.join(", ")
    )
}

pub fn build_insert_sql(table: &str, insert_columns: &[&str], insert_values: &[&str]) -> String {
    render_insert_sql(current_backend(), table, insert_columns, insert_values)
}

pub fn build_insert_if_absent_sql(
    table: &str,
    insert_columns: &[&str],
    insert_values: &[&str],
    conflict_columns: &[&str],
) -> String {
    render_insert_if_absent_sql(
        current_backend(),
        table,
        insert_columns,
        insert_values,
        conflict_columns,
    )
}

pub fn backend_placeholder(index: usize) -> String {
    current_backend().placeholder(index)
}

pub fn normalize_sql(sql: &str, start_index: usize) -> String {
    current_backend().normalize_sql(sql, start_index)
}

pub fn build_upsert_sql(
    table: &str,
    insert_columns: &[&str],
    insert_values: &[&str],
    conflict_columns: &[&str],
    update_columns: &[&str],
    update_updated_at: bool,
) -> String {
    render_upsert_sql(
        current_backend(),
        table,
        insert_columns,
        insert_values,
        conflict_columns,
        update_columns,
        update_updated_at,
    )
}
type EntityMatcher<T> = Arc<dyn Fn(&T) -> crate::Result<bool> + Send + Sync>;

struct PoolRef<'a, B: OrmBackend> {
    pool: &'a B::Pool,
}

impl<B: OrmBackend> PoolProvider<B> for PoolRef<'_, B> {
    fn pool(&self) -> &B::Pool {
        self.pool
    }
}

#[derive(Clone)]
struct ProjectionQueryState<P, B: OrmBackend>
where
    P: ReadProjection<B>,
{
    where_clauses: Vec<String>,
    values: Vec<SqlValue>,
    order_clauses: Vec<String>,
    limit: Option<i64>,
    requires_in_memory_filtering: bool,
    _marker: PhantomData<(P, B)>,
}

impl<P, B> ProjectionQueryState<P, B>
where
    B: OrmBackend,
    P: ReadProjection<B>,
{
    fn new() -> Self {
        Self {
            where_clauses: Vec::new(),
            values: Vec::new(),
            order_clauses: Vec::new(),
            limit: None,
            requires_in_memory_filtering: false,
            _marker: PhantomData,
        }
    }

    fn filter(mut self, filter: P::Filter) -> Self {
        if filter.requires_in_memory_filtering(B::DIALECT) {
            self.requires_in_memory_filtering = true;
        } else {
            let (conditions, values) = filter.to_sql_conditions();
            self.where_clauses.extend(conditions);
            self.values.extend(values);
        }
        self
    }

    fn order_by(mut self, order: P::Order) -> Self {
        if let Some(sort) = order.to_sort_expression() {
            self.order_clauses.push(sort.clause);
        }
        self
    }

    fn where_columns(mut self, columns: &[&str], values: Vec<SqlValue>) -> Self {
        debug_assert_eq!(columns.len(), values.len());
        self.where_clauses
            .extend(columns.iter().enumerate().map(|(index, column)| {
                format!(
                    "{} = {}",
                    B::DIALECT.quote_identifier_path(column),
                    B::DIALECT.placeholder(index + 1)
                )
            }));
        self.values.extend(values);
        self
    }

    fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    fn render(
        &self,
        pagination_config: PaginationConfig,
        forced_limit: Option<i64>,
    ) -> RenderedQuery {
        let entity_default = <P::Entity as DatabaseEntity>::DEFAULT_SORT;
        let mut sorts = if self.order_clauses.is_empty() {
            vec![SortExpression {
                clause: entity_default.to_string(),
            }]
        } else {
            self.order_clauses
                .iter()
                .cloned()
                .map(|clause| SortExpression { clause })
                .collect::<Vec<_>>()
        };
        for primary_key in <P::Entity as DatabaseEntity>::PRIMARY_KEYS {
            if !sorts.iter().any(|sort| {
                sort.clause
                    .split_whitespace()
                    .any(|part| part.trim_matches('"') == *primary_key)
            }) {
                sorts.push(SortExpression {
                    clause: format!("{primary_key} ASC"),
                });
            }
        }
        let page = PageInput {
            limit: forced_limit.or(self.limit),
            offset: None,
        };
        render_select_query(
            B::DIALECT,
            &SelectQuery {
                table: <P::Entity as DatabaseEntity>::TABLE_NAME,
                columns: P::COLUMNS
                    .iter()
                    .map(|column| (*column).to_string())
                    .collect(),
                filter: filter_expression_from_raw_parts(&self.where_clauses, &self.values),
                sorts,
                pagination: Some(pagination_config.resolve_page(Some(&page), true)),
                count_only: false,
            },
        )
    }

    fn validate(&self) -> crate::Result<()> {
        if self.requires_in_memory_filtering {
            return Err(sqlx::Error::Protocol(
                "projection filter requires full-entity in-memory evaluation and was rejected"
                    .to_string(),
            ));
        }
        Ok(())
    }

    fn decode(rows: Vec<B::Row>) -> crate::Result<Vec<P>> {
        rows.iter().map(P::from_row).collect()
    }
}

async fn ensure_projection_access<P, B>(db: &crate::db::Database<B>) -> crate::Result<()>
where
    B: OrmBackend,
    P: ReadProjection<B>,
{
    let metadata = P::Entity::metadata();
    db.ensure_entity_access(
        None,
        metadata.entity_name,
        metadata.read_policy,
        super::core::EntityAccessKind::Read,
        super::core::EntityAccessSurface::Repository,
    )
    .await
    .map_err(|error| sqlx::Error::Protocol(format!("{error:?}")))?;
    for selected in P::FIELD_NAMES {
        let Some(field) = <P::Entity as Entity>::repository_field_policies()
            .iter()
            .find(|field| field.rust_name == *selected)
        else {
            return Err(sqlx::Error::Protocol(format!(
                "projection field metadata is missing for {}.{selected}",
                metadata.entity_name
            )));
        };
        db.ensure_repository_readable_field(
            None,
            metadata.entity_name,
            field.api_name,
            field.read_policy,
            None,
        )
        .await
        .map_err(crate::graphql::errors::sqlx_error_from_public)?;
    }
    if db.row_policy().is_some() {
        return Err(sqlx::Error::Protocol(
            "projection reads are denied when an application row policy requires a full entity; use database RLS or a typed SQL-renderable filter"
                .to_string(),
        ));
    }
    Ok(())
}

/// Backend-neutral repository query for one macro-generated projection DTO.
pub struct ProjectionQuery<'a, P, B: OrmBackend = DefaultBackend>
where
    P: ReadProjection<B>,
{
    db: &'a crate::db::Database<B>,
    auth: Option<DbAuthContext>,
    state: ProjectionQueryState<P, B>,
}

impl<'a, P, B> ProjectionQuery<'a, P, B>
where
    B: OrmBackend,
    P: ReadProjection<B>,
{
    pub fn new(db: &'a crate::db::Database<B>) -> Self {
        Self {
            db,
            auth: None,
            state: ProjectionQueryState::new(),
        }
    }

    /// Apply backend-neutral transaction-style database auth to this read.
    pub fn with_auth(mut self, auth: Option<&DbAuthContext>) -> Self {
        self.auth = auth.cloned();
        self
    }

    pub fn filter(mut self, filter: P::Filter) -> Self {
        self.state = self.state.filter(filter);
        self
    }

    pub fn order_by(mut self, order: P::Order) -> Self {
        self.state = self.state.order_by(order);
        self
    }

    /// Request a bounded result count. Runtime maximum limits are applied
    /// before SQL execution.
    pub fn limit(mut self, limit: i64) -> Self {
        self.state = self.state.limit(limit);
        self
    }

    #[doc(hidden)]
    pub fn __where_primary_key(mut self, values: Vec<SqlValue>) -> Self {
        self.state = self
            .state
            .where_columns(<P::Entity as DatabaseEntity>::PRIMARY_KEYS, values);
        self
    }

    #[doc(hidden)]
    pub fn __where_unique(mut self, index: usize, value: SqlValue) -> Self {
        let column = P::UNIQUE_COLUMNS
            .get(index)
            .expect("macro-generated projection unique-column index");
        self.state = self.state.where_columns(&[column], vec![value]);
        self
    }

    pub async fn fetch_all(self) -> crate::Result<Vec<P>> {
        ensure_projection_access::<P, B>(self.db).await?;
        self.state.validate()?;
        let rendered = self.state.render(self.db.pagination_config(), None);
        let rows = B::fetch_rows_with_auth(
            self.db.pool(),
            &rendered.sql,
            &rendered.values,
            self.auth.as_ref(),
        )
        .await?;
        ProjectionQueryState::<P, B>::decode(rows)
    }

    pub async fn fetch_first(self) -> crate::Result<Option<P>> {
        ensure_projection_access::<P, B>(self.db).await?;
        self.state.validate()?;
        let rendered = self.state.render(self.db.pagination_config(), Some(1));
        let rows = B::fetch_rows_with_auth(
            self.db.pool(),
            &rendered.sql,
            &rendered.values,
            self.auth.as_ref(),
        )
        .await?;
        Ok(ProjectionQueryState::<P, B>::decode(rows)?
            .into_iter()
            .next())
    }

    pub async fn fetch_optional_one(self) -> crate::Result<Option<P>> {
        ensure_projection_access::<P, B>(self.db).await?;
        self.state.validate()?;
        let rendered = self.state.render(self.db.pagination_config(), Some(2));
        let rows = B::fetch_rows_with_auth(
            self.db.pool(),
            &rendered.sql,
            &rendered.values,
            self.auth.as_ref(),
        )
        .await?;
        let mut values = ProjectionQueryState::<P, B>::decode(rows)?;
        if values.len() > 1 {
            return Err(sqlx::Error::Protocol(
                "projection optional-one query matched more than one row".to_string(),
            ));
        }
        Ok(values.pop())
    }
}

#[cfg(any(feature = "sqlite", feature = "postgres"))]
/// Transaction-bound backend-neutral query for one projection DTO.
pub struct TransactionProjectionQuery<'ctx, 'tx, P, B: WriteBackend>
where
    P: ReadProjection<B>,
{
    context: &'ctx mut MutationContext<'tx, B>,
    state: ProjectionQueryState<P, B>,
}

#[cfg(any(feature = "sqlite", feature = "postgres"))]
impl<'ctx, 'tx, P, B> TransactionProjectionQuery<'ctx, 'tx, P, B>
where
    B: WriteBackend,
    for<'c> &'c mut <B::Database as sqlx::Database>::Connection:
        sqlx::Executor<'c, Database = B::Database> + Send,
    P: ReadProjection<B>,
{
    pub(crate) fn new(context: &'ctx mut MutationContext<'tx, B>) -> Self {
        Self {
            context,
            state: ProjectionQueryState::new(),
        }
    }

    pub fn filter(mut self, filter: P::Filter) -> Self {
        self.state = self.state.filter(filter);
        self
    }

    pub fn order_by(mut self, order: P::Order) -> Self {
        self.state = self.state.order_by(order);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.state = self.state.limit(limit);
        self
    }

    #[doc(hidden)]
    pub fn __where_primary_key(mut self, values: Vec<SqlValue>) -> Self {
        self.state = self
            .state
            .where_columns(<P::Entity as DatabaseEntity>::PRIMARY_KEYS, values);
        self
    }

    #[doc(hidden)]
    pub fn __where_unique(mut self, index: usize, value: SqlValue) -> Self {
        let column = P::UNIQUE_COLUMNS
            .get(index)
            .expect("macro-generated projection unique-column index");
        self.state = self.state.where_columns(&[column], vec![value]);
        self
    }

    async fn fetch(self, forced_limit: Option<i64>) -> crate::Result<Vec<P>> {
        ensure_projection_access::<P, B>(self.context.database()).await?;
        self.state.validate()?;
        let rendered = self
            .state
            .render(self.context.database().pagination_config(), forced_limit);
        let rows = B::fetch_rows_on(self.context.executor(), rendered.sql, rendered.values).await?;
        ProjectionQueryState::<P, B>::decode(rows)
    }

    pub async fn fetch_all(self) -> crate::Result<Vec<P>> {
        self.fetch(None).await
    }

    pub async fn fetch_first(self) -> crate::Result<Option<P>> {
        Ok(self.fetch(Some(1)).await?.into_iter().next())
    }

    pub async fn fetch_optional_one(self) -> crate::Result<Option<P>> {
        let mut values = self.fetch(Some(2)).await?;
        if values.len() > 1 {
            return Err(sqlx::Error::Protocol(
                "projection optional-one query matched more than one row".to_string(),
            ));
        }
        Ok(values.pop())
    }
}

pub struct EntityQuery<T, B: OrmBackend = DefaultBackend> {
    pub where_clauses: Vec<String>,
    pub values: Vec<SqlValue>,
    pub order_clauses: Vec<String>,
    pub page: Option<PageInput>,
    entity_matchers: Vec<EntityMatcher<T>>,
    _marker: PhantomData<(T, B)>,
}

impl<T, B: OrmBackend> Clone for EntityQuery<T, B> {
    fn clone(&self) -> Self {
        Self {
            where_clauses: self.where_clauses.clone(),
            values: self.values.clone(),
            order_clauses: self.order_clauses.clone(),
            page: self.page.clone(),
            entity_matchers: self.entity_matchers.clone(),
            _marker: PhantomData,
        }
    }
}

impl<T, B> EntityQuery<T, B>
where
    B: OrmBackend,
    T: DatabaseEntity + FromSqlRow<B> + Clone + Send + Sync + 'static,
{
    pub fn new() -> Self {
        Self {
            where_clauses: Vec::new(),
            values: Vec::new(),
            order_clauses: Vec::new(),
            page: None,
            entity_matchers: Vec::new(),
            _marker: PhantomData,
        }
    }

    pub fn where_clause(mut self, clause: &str, value: SqlValue) -> Self {
        self.where_clauses.push(clause.to_string());
        self.values.push(value);
        self
    }

    pub fn where_values(mut self, clause: &str, values: Vec<SqlValue>) -> Self {
        self.where_clauses.push(clause.to_string());
        self.values.extend(values);
        self
    }

    pub fn filter<F>(mut self, filter: &F) -> Self
    where
        F: DatabaseFilter,
    {
        let (conds, values) = filter.to_sql_conditions();
        self.where_clauses.extend(conds);
        self.values.extend(values);
        self
    }

    pub fn filter_with_entity_matching<F>(mut self, filter: &F) -> Self
    where
        F: DatabaseFilter + Clone + Send + Sync + 'static,
    {
        if filter.requires_in_memory_filtering(B::DIALECT) {
            let (conds, values) = filter.to_sql_prefilter_conditions(B::DIALECT);
            self.where_clauses.extend(conds);
            self.values.extend(values);
            let filter = filter.clone();
            self.entity_matchers
                .push(Arc::new(move |entity| filter.matches_entity(entity)));
        } else {
            let (conds, values) = filter.to_sql_conditions();
            self.where_clauses.extend(conds);
            self.values.extend(values);
        }
        self
    }

    pub fn order_by<O>(mut self, order: &O) -> Self
    where
        O: DatabaseOrderBy,
    {
        if let Some(sort) = order.to_sort_expression() {
            self.order_clauses.push(sort.clause);
        }
        self
    }

    pub fn default_order(mut self) -> Self {
        self.order_clauses.push(T::DEFAULT_SORT.to_string());
        self
    }

    pub fn paginate(mut self, page: &PageInput) -> Self {
        self.page = Some(page.clone());
        self
    }

    fn build_select_query_with_config(
        &self,
        pagination_config: PaginationConfig,
        apply_default_limit: bool,
    ) -> SelectQuery {
        let page = pagination_config.resolve_page(self.page.as_ref(), apply_default_limit);
        SelectQuery {
            table: T::TABLE_NAME,
            columns: T::column_names()
                .iter()
                .map(|column| (*column).to_string())
                .collect(),
            filter: filter_expression_from_raw_parts(&self.where_clauses, &self.values),
            sorts: self
                .order_clauses
                .iter()
                .cloned()
                .map(|clause| SortExpression { clause })
                .collect(),
            pagination: if self.requires_in_memory_filtering() {
                None
            } else if page.limit.is_some() || page.offset > 0 {
                Some(page)
            } else {
                None
            },
            count_only: false,
        }
    }

    fn build_select_query(&self) -> SelectQuery {
        self.build_select_query_with_config(PaginationConfig::default(), false)
    }

    fn aggregate_column_sql(column: &str) -> crate::Result<String>
    where
        T: DatabaseSchema,
    {
        let column_def = T::columns()
            .iter()
            .find(|definition| definition.name == column || definition.rust_name == column)
            .ok_or_else(|| sqlx::Error::ColumnNotFound(column.to_string()))?;
        Ok(B::DIALECT.quote_identifier_path(column_def.name))
    }

    fn build_aggregate_query(
        &self,
        function: AggregateFunction,
        column: Option<&str>,
    ) -> crate::Result<AggregateQuery>
    where
        T: DatabaseSchema,
    {
        if self.requires_in_memory_filtering() {
            return Err(sqlx::Error::Protocol(
                "aggregate queries require filters that can be rendered to SQL".to_string(),
            ));
        }
        let column = column.map(Self::aggregate_column_sql).transpose()?;
        Ok(AggregateQuery {
            table: T::TABLE_NAME,
            function,
            column,
            filter: filter_expression_from_raw_parts(&self.where_clauses, &self.values),
        })
    }

    pub(crate) fn requires_in_memory_filtering(&self) -> bool {
        !self.entity_matchers.is_empty()
    }

    fn matches_entity(&self, entity: &T) -> crate::Result<bool> {
        self.entity_matchers
            .iter()
            .try_fold(
                true,
                |matches, matcher| {
                    if matches { matcher(entity) } else { Ok(false) }
                },
            )
    }

    fn apply_in_memory_filtering(
        &self,
        rows: Vec<B::Row>,
        pagination_config: PaginationConfig,
        apply_default_limit: bool,
    ) -> crate::Result<Vec<T>> {
        let mut entities = rows
            .iter()
            .map(T::from_row)
            .collect::<Result<Vec<_>, _>>()?;

        if self.requires_in_memory_filtering() {
            entities = entities
                .into_iter()
                .filter_map(|entity| match self.matches_entity(&entity) {
                    Ok(true) => Some(Ok(entity)),
                    Ok(false) => None,
                    Err(error) => Some(Err(error)),
                })
                .collect::<Result<Vec<_>, _>>()?;

            let page = pagination_config.resolve_page(self.page.as_ref(), apply_default_limit);
            if page.limit.is_some() || page.offset > 0 {
                let offset = page.offset.max(0) as usize;
                let limit = page.limit.map(|limit| limit.max(0) as usize);
                let iter = entities.into_iter().skip(offset);
                entities = match limit {
                    Some(limit) => iter.take(limit).collect(),
                    None => iter.collect(),
                };
            }
        }

        Ok(entities)
    }

    async fn fetch_unpaged_filtered<P>(&self, provider: &P) -> crate::Result<Vec<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        let mut query = self.clone();
        query.page = None;
        query.fetch_all(provider).await
    }

    async fn fetch_unpaged_filtered_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
    ) -> crate::Result<Vec<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        let mut query = self.clone();
        query.page = None;
        query.fetch_all_with_auth(provider, auth).await
    }

    pub async fn fetch_all<P>(&self, provider: &P) -> crate::Result<Vec<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        let pagination_config = provider.pagination_config();
        let rendered = render_select_query(
            B::DIALECT,
            &self.build_select_query_with_config(pagination_config, false),
        );
        let rows = B::fetch_rows(provider.pool(), &rendered.sql, &rendered.values).await?;
        self.apply_in_memory_filtering(rows, pagination_config, false)
    }

    pub async fn fetch_all_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
    ) -> crate::Result<Vec<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        let pagination_config = provider.pagination_config();
        let rendered = render_select_query(
            B::DIALECT,
            &self.build_select_query_with_config(pagination_config, false),
        );
        let rows =
            B::fetch_rows_with_auth(provider.pool(), &rendered.sql, &rendered.values, auth).await?;
        self.apply_in_memory_filtering(rows, pagination_config, false)
    }

    pub(crate) async fn fetch_all_with_auth_and_pagination<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
        pagination_config: PaginationConfig,
    ) -> crate::Result<Vec<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        let rendered = render_select_query(
            B::DIALECT,
            &self.build_select_query_with_config(pagination_config, false),
        );
        let rows =
            B::fetch_rows_with_auth(provider.pool(), &rendered.sql, &rendered.values, auth).await?;
        self.apply_in_memory_filtering(rows, pagination_config, false)
    }

    pub async fn fetch_all_on<'e, E>(&self, executor: E) -> crate::Result<Vec<T>>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        let rendered = render_select_query(B::DIALECT, &self.build_select_query());
        let rows = B::fetch_rows_on(executor, rendered.sql, rendered.values).await?;
        self.apply_in_memory_filtering(rows, PaginationConfig::default(), false)
    }

    #[cfg(any(feature = "sqlite", feature = "postgres"))]
    pub(crate) async fn fetch_bounded_mutation_sentinel_on<'e, E>(
        &self,
        executor: E,
        limit: MutationLimit,
    ) -> crate::Result<Vec<T>>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        if self.requires_in_memory_filtering() {
            return Err(crate::graphql::errors::sqlx_error_from_public(
                crate::graphql::errors::OrmPublicError::new(
                    crate::graphql::errors::OrmErrorCode::InvalidInput,
                )
                .with_internal(
                    "bounded mutations require a filter rendered completely by the database",
                ),
            ));
        }

        let sentinel_limit = i64::from(limit.get()).checked_add(1).ok_or_else(|| {
            crate::graphql::errors::sqlx_error_from_public(
                crate::graphql::errors::OrmPublicError::new(
                    crate::graphql::errors::OrmErrorCode::InternalError,
                )
                .with_internal("bounded mutation sentinel limit overflow"),
            )
        })?;
        let mut query = self.clone();
        query.order_clauses = vec![
            T::PRIMARY_KEYS
                .iter()
                .map(|column| B::DIALECT.quote_identifier_path(column))
                .collect::<Vec<_>>()
                .join(", "),
        ];
        query.page = Some(PageInput {
            limit: Some(sentinel_limit),
            offset: Some(0),
        });
        let pagination = PaginationConfig::unbounded();
        let rendered = render_select_query(
            B::DIALECT,
            &query.build_select_query_with_config(pagination, false),
        );
        let rows = B::fetch_rows_on(executor, rendered.sql, rendered.values).await?;
        query.apply_in_memory_filtering(rows, pagination, false)
    }

    pub async fn fetch_one<P>(&self, provider: &P) -> crate::Result<Option<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        Ok(self.fetch_all(provider).await?.into_iter().next())
    }

    pub async fn fetch_one_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
    ) -> crate::Result<Option<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        Ok(self
            .fetch_all_with_auth(provider, auth)
            .await?
            .into_iter()
            .next())
    }

    pub async fn fetch_one_on<'e, E>(&self, executor: E) -> crate::Result<Option<T>>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        Ok(self.fetch_all_on(executor).await?.into_iter().next())
    }

    pub async fn count<P>(&self, provider: &P) -> crate::Result<i64>
    where
        P: PoolProvider<B> + ?Sized,
    {
        if self.requires_in_memory_filtering() {
            return Ok(self.fetch_unpaged_filtered(provider).await?.len() as i64);
        }
        let mut query = self.build_select_query();
        query.count_only = true;
        query.pagination = None;
        query.sorts.clear();
        let rendered = render_select_query(B::DIALECT, &query);
        let rows = B::fetch_rows(provider.pool(), &rendered.sql, &rendered.values).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_i64(row, "count")
    }

    pub async fn count_column<P>(&self, provider: &P, column: &str) -> crate::Result<i64>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        let rendered = render_aggregate_query(
            B::DIALECT,
            &self.build_aggregate_query(AggregateFunction::Count, Some(column))?,
        );
        let rows = B::fetch_rows(provider.pool(), &rendered.sql, &rendered.values).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_i64(row, "__gom_aggregate")
    }

    pub async fn max_i64<P>(&self, provider: &P, column: &str) -> crate::Result<Option<i64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        self.aggregate_optional_i64(provider, AggregateFunction::Max, column)
            .await
    }

    pub async fn min_i64<P>(&self, provider: &P, column: &str) -> crate::Result<Option<i64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        self.aggregate_optional_i64(provider, AggregateFunction::Min, column)
            .await
    }

    pub async fn max_f64<P>(&self, provider: &P, column: &str) -> crate::Result<Option<f64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        self.aggregate_optional_f64(provider, AggregateFunction::Max, column)
            .await
    }

    pub async fn min_f64<P>(&self, provider: &P, column: &str) -> crate::Result<Option<f64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        self.aggregate_optional_f64(provider, AggregateFunction::Min, column)
            .await
    }

    async fn aggregate_optional_i64<P>(
        &self,
        provider: &P,
        function: AggregateFunction,
        column: &str,
    ) -> crate::Result<Option<i64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        let rendered = render_aggregate_query(
            B::DIALECT,
            &self.build_aggregate_query(function, Some(column))?,
        );
        let rows = B::fetch_rows(provider.pool(), &rendered.sql, &rendered.values).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_optional_i64(row, "__gom_aggregate")
    }

    async fn aggregate_optional_f64<P>(
        &self,
        provider: &P,
        function: AggregateFunction,
        column: &str,
    ) -> crate::Result<Option<f64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        let rendered = render_aggregate_query(
            B::DIALECT,
            &self.build_aggregate_query(function, Some(column))?,
        );
        let rows = B::fetch_rows(provider.pool(), &rendered.sql, &rendered.values).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_optional_f64(row, "__gom_aggregate")
    }

    pub async fn count_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
    ) -> crate::Result<i64>
    where
        P: PoolProvider<B> + ?Sized,
    {
        if self.requires_in_memory_filtering() {
            return Ok(self
                .fetch_unpaged_filtered_with_auth(provider, auth)
                .await?
                .len() as i64);
        }
        let mut query = self.build_select_query();
        query.count_only = true;
        query.pagination = None;
        query.sorts.clear();
        let rendered = render_select_query(B::DIALECT, &query);
        let rows =
            B::fetch_rows_with_auth(provider.pool(), &rendered.sql, &rendered.values, auth).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_i64(row, "count")
    }

    pub async fn count_column_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
        column: &str,
    ) -> crate::Result<i64>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        let rendered = render_aggregate_query(
            B::DIALECT,
            &self.build_aggregate_query(AggregateFunction::Count, Some(column))?,
        );
        let rows =
            B::fetch_rows_with_auth(provider.pool(), &rendered.sql, &rendered.values, auth).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_i64(row, "__gom_aggregate")
    }

    pub async fn max_i64_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
        column: &str,
    ) -> crate::Result<Option<i64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        self.aggregate_optional_i64_with_auth(provider, auth, AggregateFunction::Max, column)
            .await
    }

    pub async fn min_i64_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
        column: &str,
    ) -> crate::Result<Option<i64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        self.aggregate_optional_i64_with_auth(provider, auth, AggregateFunction::Min, column)
            .await
    }

    async fn aggregate_optional_i64_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
        function: AggregateFunction,
        column: &str,
    ) -> crate::Result<Option<i64>>
    where
        P: PoolProvider<B> + ?Sized,
        T: DatabaseSchema,
    {
        let rendered = render_aggregate_query(
            B::DIALECT,
            &self.build_aggregate_query(function, Some(column))?,
        );
        let rows =
            B::fetch_rows_with_auth(provider.pool(), &rendered.sql, &rendered.values, auth).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_optional_i64(row, "__gom_aggregate")
    }

    pub async fn count_on<'e, E>(&self, executor: E) -> crate::Result<i64>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        if self.requires_in_memory_filtering() {
            let mut query = self.clone();
            query.page = None;
            return Ok(query.fetch_all_on(executor).await?.len() as i64);
        }
        let mut query = self.build_select_query();
        query.count_only = true;
        query.pagination = None;
        query.sorts.clear();
        let rendered = render_select_query(B::DIALECT, &query);
        let rows = B::fetch_rows_on(executor, rendered.sql, rendered.values).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_i64(row, "count")
    }

    pub fn build_delete_sql(&self) -> (String, Vec<SqlValue>) {
        let rendered = render_delete_query(
            B::DIALECT,
            &DeleteQuery {
                table: T::TABLE_NAME,
                filter: filter_expression_from_raw_parts(&self.where_clauses, &self.values),
            },
        );
        (rendered.sql, rendered.values)
    }

    pub async fn fetch_connection<P>(&self, provider: &P) -> crate::Result<Connection<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        if self.requires_in_memory_filtering() {
            let nodes = self.fetch_unpaged_filtered(provider).await?;
            let total = nodes.len() as i64;
            let page = provider
                .pagination_config()
                .resolve_page(self.page.as_ref(), true);
            let offset = page.offset.max(0) as usize;
            let limit = page.limit.map(|limit| limit.max(0) as usize);
            let page_nodes = if offset >= nodes.len() {
                Vec::new()
            } else {
                let iter = nodes.into_iter().skip(offset);
                match limit {
                    Some(limit) => iter.take(limit).collect(),
                    None => iter.collect(),
                }
            };
            let edges = page_nodes
                .into_iter()
                .enumerate()
                .map(|(index, node)| Edge {
                    node,
                    cursor: encode_cursor((offset + index) as i64),
                })
                .collect::<Vec<_>>();

            return Ok(Connection {
                page_info: PageInfo {
                    has_next_page: (offset as i64 + edges.len() as i64) < total,
                    has_previous_page: offset > 0,
                    start_cursor: edges.first().map(|edge| edge.cursor.clone()),
                    end_cursor: edges.last().map(|edge| edge.cursor.clone()),
                    total_count: Some(total),
                },
                edges,
            });
        }
        let pagination_config = provider.pagination_config();
        let page = pagination_config.resolve_page(self.page.as_ref(), true);
        let offset = page.offset.max(0) as usize;
        let mut count_query = self.build_select_query();
        count_query.count_only = true;
        count_query.pagination = None;
        count_query.sorts.clear();
        let count_rendered = render_select_query(B::DIALECT, &count_query);
        let row_rendered = render_select_query(
            B::DIALECT,
            &self.build_select_query_with_config(pagination_config, true),
        );
        let (count_rows, rows) = B::fetch_rows_pair_with_auth(
            provider.pool(),
            &count_rendered.sql,
            &count_rendered.values,
            &row_rendered.sql,
            &row_rendered.values,
            None,
        )
        .await?;
        let count_row = count_rows.first().ok_or(sqlx::Error::RowNotFound)?;
        let total = B::try_get_i64(count_row, "count")?;
        let nodes = rows
            .iter()
            .map(T::from_row)
            .collect::<Result<Vec<_>, _>>()?;
        let edges = nodes
            .into_iter()
            .enumerate()
            .map(|(index, node)| Edge {
                node,
                cursor: encode_cursor((offset + index) as i64),
            })
            .collect::<Vec<_>>();

        Ok(Connection {
            page_info: PageInfo {
                has_next_page: (offset as i64 + edges.len() as i64) < total,
                has_previous_page: offset > 0,
                start_cursor: edges.first().map(|edge| edge.cursor.clone()),
                end_cursor: edges.last().map(|edge| edge.cursor.clone()),
                total_count: Some(total),
            },
            edges,
        })
    }

    pub async fn fetch_connection_with_auth<P>(
        &self,
        provider: &P,
        auth: Option<&DbAuthContext>,
    ) -> crate::Result<Connection<T>>
    where
        P: PoolProvider<B> + ?Sized,
    {
        if self.requires_in_memory_filtering() {
            let nodes = self
                .fetch_unpaged_filtered_with_auth(provider, auth)
                .await?;
            let total = nodes.len() as i64;
            let page = provider
                .pagination_config()
                .resolve_page(self.page.as_ref(), true);
            let offset = page.offset.max(0) as usize;
            let limit = page.limit.map(|limit| limit.max(0) as usize);
            let page_nodes = if offset >= nodes.len() {
                Vec::new()
            } else {
                let iter = nodes.into_iter().skip(offset);
                match limit {
                    Some(limit) => iter.take(limit).collect(),
                    None => iter.collect(),
                }
            };
            let edges = page_nodes
                .into_iter()
                .enumerate()
                .map(|(index, node)| Edge {
                    node,
                    cursor: encode_cursor((offset + index) as i64),
                })
                .collect::<Vec<_>>();

            return Ok(Connection {
                page_info: PageInfo {
                    has_next_page: (offset as i64 + edges.len() as i64) < total,
                    has_previous_page: offset > 0,
                    start_cursor: edges.first().map(|edge| edge.cursor.clone()),
                    end_cursor: edges.last().map(|edge| edge.cursor.clone()),
                    total_count: Some(total),
                },
                edges,
            });
        }
        let mut count_query = self.build_select_query();
        count_query.count_only = true;
        count_query.pagination = None;
        count_query.sorts.clear();
        let count_rendered = render_select_query(B::DIALECT, &count_query);
        let pagination_config = provider.pagination_config();
        let row_rendered = render_select_query(
            B::DIALECT,
            &self.build_select_query_with_config(pagination_config, true),
        );
        let (count_rows, rows) = B::fetch_rows_pair_with_auth(
            provider.pool(),
            &count_rendered.sql,
            &count_rendered.values,
            &row_rendered.sql,
            &row_rendered.values,
            auth,
        )
        .await?;
        let count_row = count_rows.first().ok_or(sqlx::Error::RowNotFound)?;
        let total = B::try_get_i64(count_row, "count")?;
        let page = pagination_config.resolve_page(self.page.as_ref(), true);
        let offset = page.offset.max(0) as usize;
        let nodes = rows
            .iter()
            .map(T::from_row)
            .collect::<Result<Vec<_>, _>>()?;
        let edges = nodes
            .into_iter()
            .enumerate()
            .map(|(index, node)| Edge {
                node,
                cursor: encode_cursor((offset + index) as i64),
            })
            .collect::<Vec<_>>();

        Ok(Connection {
            page_info: PageInfo {
                has_next_page: (offset as i64 + edges.len() as i64) < total,
                has_previous_page: offset > 0,
                start_cursor: edges.first().map(|edge| edge.cursor.clone()),
                end_cursor: edges.last().map(|edge| edge.cursor.clone()),
                total_count: Some(total),
            },
            edges,
        })
    }
}

pub struct FindQuery<'a, T, W, O, B: OrmBackend = DefaultBackend>
where
    T: DatabaseEntity + FromSqlRow<B> + Clone + Send + Sync + 'static,
{
    pool: &'a B::Pool,
    query: EntityQuery<T, B>,
    _marker: PhantomData<(W, O, B)>,
}

impl<'a, T, W, O, B> FindQuery<'a, T, W, O, B>
where
    B: OrmBackend,
    T: DatabaseEntity + FromSqlRow<B> + Clone + Send + Sync + 'static,
    W: DatabaseFilter + Clone + Send + Sync + 'static,
{
    pub fn new(pool: &'a B::Pool) -> Self {
        Self {
            pool,
            query: EntityQuery::new(),
            _marker: PhantomData,
        }
    }

    pub fn filter(mut self, filter: W) -> Self {
        self.query = self.query.filter_with_entity_matching(&filter);
        self
    }

    pub fn order_by(mut self, order: O) -> Self
    where
        O: DatabaseOrderBy,
    {
        self.query = self.query.order_by(&order);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        let mut page = self.query.page.unwrap_or_default();
        page.limit = Some(limit);
        self.query.page = Some(page);
        self
    }

    pub fn offset(mut self, offset: i64) -> Self {
        let mut page = self.query.page.unwrap_or_default();
        page.offset = Some(offset);
        self.query.page = Some(page);
        self
    }

    pub async fn fetch_all(self) -> crate::Result<Vec<T>> {
        self.query.fetch_all(&PoolRef { pool: self.pool }).await
    }

    pub async fn fetch_all_on<'e, E>(self, executor: E) -> crate::Result<Vec<T>>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        self.query.fetch_all_on(executor).await
    }

    pub async fn fetch_one(self) -> crate::Result<Option<T>> {
        Ok(self.fetch_all().await?.into_iter().next())
    }

    pub async fn fetch_one_on<'e, E>(self, executor: E) -> crate::Result<Option<T>>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        self.query.fetch_one_on(executor).await
    }

    pub async fn count(self) -> crate::Result<i64> {
        self.query.count(&PoolRef { pool: self.pool }).await
    }

    pub async fn count_column(self, column: &str) -> crate::Result<i64>
    where
        T: DatabaseSchema,
    {
        self.query
            .count_column(&PoolRef { pool: self.pool }, column)
            .await
    }

    pub async fn max_i64(self, column: &str) -> crate::Result<Option<i64>>
    where
        T: DatabaseSchema,
    {
        self.query
            .max_i64(&PoolRef { pool: self.pool }, column)
            .await
    }

    pub async fn min_i64(self, column: &str) -> crate::Result<Option<i64>>
    where
        T: DatabaseSchema,
    {
        self.query
            .min_i64(&PoolRef { pool: self.pool }, column)
            .await
    }

    pub async fn max_f64(self, column: &str) -> crate::Result<Option<f64>>
    where
        T: DatabaseSchema,
    {
        self.query
            .max_f64(&PoolRef { pool: self.pool }, column)
            .await
    }

    pub async fn min_f64(self, column: &str) -> crate::Result<Option<f64>>
    where
        T: DatabaseSchema,
    {
        self.query
            .min_f64(&PoolRef { pool: self.pool }, column)
            .await
    }

    pub async fn count_on<'e, E>(self, executor: E) -> crate::Result<i64>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        self.query.count_on(executor).await
    }

    pub async fn exists(self) -> crate::Result<bool> {
        Ok(self.count().await? > 0)
    }

    pub async fn exists_on<'e, E>(self, executor: E) -> crate::Result<bool>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        Ok(self.query.count_on(executor).await? > 0)
    }
}

pub struct EntityCountQuery<'a, T, W, B: OrmBackend = DefaultBackend>
where
    T: DatabaseEntity + FromSqlRow<B> + Clone + Send + Sync + 'static,
{
    pool: &'a B::Pool,
    query: EntityQuery<T, B>,
    _marker: PhantomData<W>,
}

impl<'a, T, W, B> EntityCountQuery<'a, T, W, B>
where
    B: OrmBackend,
    T: DatabaseEntity + FromSqlRow<B> + Clone + Send + Sync + 'static,
    W: DatabaseFilter + Clone + Send + Sync + 'static,
{
    pub fn new(pool: &'a B::Pool) -> Self {
        Self {
            pool,
            query: EntityQuery::new(),
            _marker: PhantomData,
        }
    }

    pub fn filter(mut self, filter: &W) -> Self {
        self.query = self.query.filter_with_entity_matching(filter);
        self
    }

    pub async fn count(self) -> crate::Result<i64> {
        self.query.count(&PoolRef { pool: self.pool }).await
    }

    pub async fn count_on<'e, E>(self, executor: E) -> crate::Result<i64>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        self.query.count_on(executor).await
    }
}

pub struct CountQuery<'a, W, B: OrmBackend = DefaultBackend> {
    pool: &'a B::Pool,
    table: &'static str,
    filters: Vec<String>,
    values: Vec<SqlValue>,
    _marker: PhantomData<(W, B)>,
}

impl<'a, W, B> CountQuery<'a, W, B>
where
    B: OrmBackend,
    W: DatabaseFilter,
{
    pub fn new(pool: &'a B::Pool, table: &'static str) -> Self {
        Self {
            pool,
            table,
            filters: Vec::new(),
            values: Vec::new(),
            _marker: PhantomData,
        }
    }

    pub fn filter(mut self, filter: &W) -> Self {
        let (conds, values) = filter.to_sql_conditions();
        self.filters.extend(conds);
        self.values.extend(values);
        self
    }

    pub async fn count(self) -> crate::Result<i64> {
        let rendered = render_select_query(
            B::DIALECT,
            &SelectQuery {
                table: self.table,
                columns: Vec::new(),
                filter: filter_expression_from_raw_parts(&self.filters, &self.values),
                sorts: Vec::new(),
                pagination: None,
                count_only: true,
            },
        );
        let rows = B::fetch_rows(self.pool, &rendered.sql, &rendered.values).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_i64(row, "count")
    }

    pub async fn count_on<'e, E>(self, executor: E) -> crate::Result<i64>
    where
        B: SqlxBackend,
        E: sqlx::Executor<'e, Database = <B as SqlxBackend>::Database> + Send + 'e,
    {
        let rendered = render_select_query(
            B::DIALECT,
            &SelectQuery {
                table: self.table,
                columns: Vec::new(),
                filter: filter_expression_from_raw_parts(&self.filters, &self.values),
                sorts: Vec::new(),
                pagination: None,
                count_only: true,
            },
        );
        let rows = B::fetch_rows_on(executor, rendered.sql, rendered.values).await?;
        let row = rows.first().ok_or(sqlx::Error::RowNotFound)?;
        B::try_get_i64(row, "count")
    }
}
