#![allow(
    clippy::collapsible_if,
    clippy::iter_cloned_collect,
    clippy::needless_lifetimes,
    clippy::new_without_default,
    clippy::too_many_arguments,
    clippy::derivable_impls,
    clippy::type_complexity,
    clippy::if_same_then_else,
    clippy::unnecessary_filter_map,
    clippy::unnecessary_sort_by,
    clippy::large_enum_variant,
    clippy::items_after_test_module,
    clippy::manual_contains
)]

//! Runtime crate for `graphql-orm`.
//!
//! `graphql-orm` combines this runtime with the `graphql-orm-macros` derive
//! crate to generate `async-graphql` queries, mutations, subscriptions,
//! filters, ordering, pagination, relation loading, schema metadata, and
//! repository helpers from Rust structs.
//!
//! # Backends
//!
//! Enable one or more backend features:
//!
//! - `sqlite`
//! - `postgres`
//! - `mssql`
//!
//! SQLite and Postgres support reads, writes, subscriptions, schema
//! validation, planning, and explicit migrations. MSSQL is read/query-only and
//! uses Tiberius instead of SQLx because current SQLx does not support SQL
//! Server.
//!
//! When exactly one backend feature is enabled, compatibility aliases
//! `DbPool` and `DbRow` are exported. When multiple backend features are
//! enabled by Cargo feature unification, generated entities and schema roots
//! must select a backend explicitly.
//!
//! # Schema Ownership
//!
//! Backend features only compile database support. Schema ownership is selected
//! at runtime with [`graphql::orm::SchemaPolicy`].
//!
//! ```ignore
//! use graphql_orm::prelude::*;
//!
//! let database = Database::<SqliteBackend>::connect_sqlite("sqlite://app.db")
//!     .await?
//!     .with_schema_policy(SchemaPolicy::Managed);
//!
//! let database = Database::builder(pool)
//!     .schema_policy(SchemaPolicy::Managed)
//!     .build();
//!
//! let report = database
//!     .schema()
//!     .validate_against_entities(&[User::metadata()])
//!     .await?;
//! ```
//!
//! `Database::new`, `Database::builder`, and GraphQL schema construction never
//! apply schema changes. Use `database.schema()` for explicit validation,
//! planning, and migration application.
//!
//! # Schema Query Limits
//!
//! Generated `schema_builder(database)` helpers apply production query safety
//! defaults: maximum GraphQL depth `16` and maximum complexity `20_000`. These
//! caps are intended to make cyclic relation traversal finite by default while
//! still allowing ordinary list, edge, node, and relation selections. Relation
//! fields generated by `GraphQLRelations` carry custom complexity costs; list
//! relations scale by the requested page size, capped at the ORM default page
//! maximum for validation-time accounting.
//!
//! Generated roots also expose `schema_builder_with_limits(database,
//! SchemaLimits { .. })`. Use [`crate::graphql::orm::SchemaLimits::unbounded`]
//! only for trusted internal schemas or tests, and prefer smaller limits for
//! public token surfaces when the application shape allows it.
//!
//! # Public Mutation Exposure
//!
//! `schema_roots!` can hide generated GraphQL mutation fields without disabling
//! generated repository writes. The default is `generated_mutations: "all"`.
//! Use `generated_mutations: "none"` when a public schema should expose only
//! custom roots from `extra_mutation_types`, or use `"allowlist"` with
//! `generated_mutation_allowlist: [Entity]` / `"denylist"` with
//! `generated_mutation_denylist: [Entity]` for mixed exposure. Generated write
//! inputs, repository helpers, mutation hooks, mutation contexts, and
//! subscriptions remain available to application code.
//!
//! # Generated Resolver Auth
//!
//! Generated resolvers understand a project-agnostic
//! [`graphql::auth::AuthSubject`] with an id, optional user id, roles, scopes,
//! tenant id, token/session references, and safe claims. Applications can
//! attach `AuthSubject` to async-graphql request data directly, or keep
//! attaching the legacy `String` user id while migrating;
//! [`graphql::auth::AuthExt::auth_subject`] upgrades legacy ids into subjects
//! with empty roles and scopes.
//!
//! Authorization policy enforcement is controlled by
//! [`graphql::auth::AuthorizationMode`]. The current default is
//! `LegacyPermissive` (missing providers allow). Production services should set
//! `DeclaredPoliciesRequired` so declared policy keys never fail open.
//!
//! Public GraphQL errors use [`graphql::errors::OrmPublicError`] so SQL and
//! configuration details stay server-side.
//!
//! ```ignore
//! schema_roots! {
//!     auth: "required",
//!     query_custom_ops: [],
//!     entities: [User],
//! }
//!
//! let request = request.data(AuthSubject::new("current-user-id"));
//! ```
//!
//! Supported generated resolver modes are `required`, `optional`, and `none`.
//! The compatibility default remains fail-closed, matching the older generated
//! `ctx.auth_user()?` gate. Use `auth = "none"` for public generated schemas.
//! [`graphql::orm::ScopeEntityPolicy`] provides exact-scope entity gates without
//! depending on any auth crate.
//!
//! # Spatial Fields
//!
//! PostgreSQL and SQLite entities can expose spatial values as GeoJSON through
//! `serde_json::Value` fields. PostgreSQL stores those fields as PostGIS
//! `geometry(<type>, <srid>)` columns and can create GiST spatial indexes.
//! SQLite stores canonical GeoJSON in `TEXT` columns and evaluates spatial
//! predicates in Rust, which keeps the entity API portable at the cost of
//! large-table query efficiency.
//!
//! ```ignore
//! #[graphql_orm(spatial(kind = "geometry", geometry_type = "Point", srid = 4326, index = true))]
//! #[filterable(type = "spatial")]
//! pub location: serde_json::Value;
//! ```
//!
//! Spatial filters support `equals`, `disjoint`, `intersects`, `touches`,
//! `crosses`, `within`, `contains`, `overlaps`, and `is_null`.
//!
//! # Full-Text Search
//!
//! Text fields can be marked searchable. Generated operations then expose a
//! backend-neutral search resolver and Rust query helper. PostgreSQL uses
//! managed `tsvector` search tables and GIN indexes. SQLite uses FTS5 where
//! available, with fallback scoring available through the runtime search
//! document path.
//!
//! ```ignore
//! #[graphql_orm(search(index = true, language = "english"))]
//! pub struct Article {
//!     #[primary_key]
//!     pub id: uuid::Uuid,
//!
//!     #[graphql_orm(searchable(weight = "A"))]
//!     pub title: String,
//!
//!     #[graphql_orm(json, read = false, filter = false, order = false, subscribe = false)]
//!     #[graphql_orm(search_json(path = "$.description.summary", weight = "C"))]
//!     #[graphql_orm(search_json(path = "$.classification.keywords[*].label", weight = "C"))]
//!     pub content: ArticleContent,
//! }
//!
//! let hits = Article::search_db(&database, SearchInput {
//!     query: "melbourne park".to_string(),
//!     mode: Some(SearchMode::Web),
//!     min_score: None,
//! })
//! .limit(20)
//! .fetch_all()
//! .await?;
//! ```
//!
//! Managed migrations create search tables and indexes, but they do not
//! backfill existing data automatically. Run the generated
//! `Entity::rebuild_search_index(&database)` helper after adding or changing a
//! search index on an existing table.
//! JSON search paths are extracted in Rust from persisted `#[graphql_orm(json)]`
//! field values and then stored in the same backend-specific search document as
//! ordinary text fields.
//!
//! Native PostgreSQL and SQLite FTS5 search paths push score, count, limit, and
//! offset into SQL. PostgreSQL requests that carry a database auth context still
//! use native search inside the same transaction-local context used for RLS.
//!
//! # Pagination And Relation Loading
//!
//! Generated connections use offset-style cursors. [`crate::graphql::orm::PageInput`]
//! clamps negative offsets to `0`. [`crate::graphql::orm::PaginationConfig`]
//! controls generated connection defaults and caps; the default configuration
//! applies a limit of `50` when `page.limit` is omitted and clamps explicit
//! limits to `100`. Use [`crate::graphql::orm::PaginationConfig::legacy`] for
//! the previous 1000/1000 behavior during migration. Repository-style
//! `fetch_all` helpers remain unbounded unless the caller supplies pagination.
//! Host code that inspects [`crate::graphql::orm::PageInput`] directly should
//! use [`crate::graphql::orm::PageInput::limit_with_config`] or
//! [`crate::graphql::orm::PaginationConfig::resolve_page`]; the legacy
//! `PageInput::limit()` helper is deprecated because it can only use the default
//! cap. Paged relation batches use backend window functions where available so
//! nested relation pages do not need to load every child row for every parent.
//!
//! # Generated Entity Example
//!
//! ```ignore
//! use graphql_orm::prelude::*;
//!
//! #[derive(GraphQLEntity, GraphQLOperations, Clone, Debug)]
//! #[graphql_entity(table = "users", plural = "Users")]
//! pub struct User {
//!     #[primary_key]
//!     pub id: i64,
//!     #[filterable]
//!     #[sortable]
//!     pub name: String,
//! }
//! ```
//!
//! See the repository `README.md` and `docs/` directory for full examples,
//! backend notes, relation batching, schema policies, and migration guidance.

pub use async_graphql;
pub use futures;
pub use graphql_orm_macros::*;
pub use serde_json;
pub use sqlx;
#[cfg(feature = "mssql")]
pub use tiberius;
pub use tokio;
pub use tokio_stream;
#[cfg(feature = "mssql")]
pub use tokio_util;
pub use uuid;

/// Public ORM error type used by generated repository helpers and runtime APIs.
///
/// This is currently an alias for the backend SQL execution error so existing
/// matching and `?` conversions remain source-compatible. Application crates
/// should name `graphql_orm::Error` in public signatures instead of importing
/// SQLX directly; the alias leaves room for a richer ORM-owned error enum in a
/// future major release.
pub type Error = sqlx::Error;

/// Public ORM result alias used by generated repository helpers and runtime APIs.
pub type Result<T> = std::result::Result<T, Error>;

#[cfg(not(any(feature = "sqlite", feature = "postgres", feature = "mssql")))]
compile_error!("Enable at least one backend feature for graphql-orm.");

#[cfg(any(
    all(feature = "resolver-case-pascal", feature = "resolver-case-snake"),
    all(
        feature = "resolver-case-pascal",
        feature = "resolver-case-screaming-snake"
    ),
    all(feature = "resolver-case-pascal", feature = "resolver-case-lower"),
    all(feature = "resolver-case-pascal", feature = "resolver-case-upper"),
    all(
        feature = "resolver-case-snake",
        feature = "resolver-case-screaming-snake"
    ),
    all(feature = "resolver-case-snake", feature = "resolver-case-lower"),
    all(feature = "resolver-case-snake", feature = "resolver-case-upper"),
    all(
        feature = "resolver-case-screaming-snake",
        feature = "resolver-case-lower"
    ),
    all(
        feature = "resolver-case-screaming-snake",
        feature = "resolver-case-upper"
    ),
    all(feature = "resolver-case-lower", feature = "resolver-case-upper")
))]
compile_error!("Enable at most one resolver-case-* feature for graphql-orm.");

#[cfg(any(
    all(feature = "argument-case-pascal", feature = "argument-case-snake"),
    all(
        feature = "argument-case-pascal",
        feature = "argument-case-screaming-snake"
    ),
    all(feature = "argument-case-pascal", feature = "argument-case-lower"),
    all(feature = "argument-case-pascal", feature = "argument-case-upper"),
    all(
        feature = "argument-case-snake",
        feature = "argument-case-screaming-snake"
    ),
    all(feature = "argument-case-snake", feature = "argument-case-lower"),
    all(feature = "argument-case-snake", feature = "argument-case-upper"),
    all(
        feature = "argument-case-screaming-snake",
        feature = "argument-case-lower"
    ),
    all(
        feature = "argument-case-screaming-snake",
        feature = "argument-case-upper"
    ),
    all(feature = "argument-case-lower", feature = "argument-case-upper")
))]
compile_error!("Enable at most one argument-case-* feature for graphql-orm.");

#[cfg(any(
    all(feature = "field-case-pascal", feature = "field-case-snake"),
    all(feature = "field-case-pascal", feature = "field-case-screaming-snake"),
    all(feature = "field-case-pascal", feature = "field-case-lower"),
    all(feature = "field-case-pascal", feature = "field-case-upper"),
    all(feature = "field-case-snake", feature = "field-case-screaming-snake"),
    all(feature = "field-case-snake", feature = "field-case-lower"),
    all(feature = "field-case-snake", feature = "field-case-upper"),
    all(feature = "field-case-screaming-snake", feature = "field-case-lower"),
    all(feature = "field-case-screaming-snake", feature = "field-case-upper"),
    all(feature = "field-case-lower", feature = "field-case-upper")
))]
compile_error!("Enable at most one field-case-* feature for graphql-orm.");

pub use crate::graphql::orm::{
    DefaultBackend, DefaultWriteBackend, IntrospectionBackend, MigrationBackend, MssqlBackend,
    NoDefaultBackend, OrmBackend, PostgresBackend, SqliteBackend, SqlxBackend, SubscriptionBackend,
    WriteBackend,
};

#[cfg(any(
    all(feature = "sqlite", not(any(feature = "postgres", feature = "mssql"))),
    all(feature = "postgres", not(any(feature = "sqlite", feature = "mssql"))),
    all(feature = "mssql", not(any(feature = "sqlite", feature = "postgres")))
))]
/// Compatibility pool alias exported only when exactly one backend feature is enabled.
///
/// In multi-backend builds, use explicit backend pool types such as
/// `<SqliteBackend as OrmBackend>::Pool` or `Database<MssqlBackend>` instead.
pub type DbPool = <DefaultBackend as OrmBackend>::Pool;

#[cfg(any(
    all(feature = "sqlite", not(any(feature = "postgres", feature = "mssql"))),
    all(feature = "postgres", not(any(feature = "sqlite", feature = "mssql"))),
    all(feature = "mssql", not(any(feature = "sqlite", feature = "postgres")))
))]
/// Compatibility row alias exported only when exactly one backend feature is enabled.
///
/// In multi-backend builds, use explicit backend row types such as
/// `<PostgresBackend as OrmBackend>::Row`.
pub type DbRow = <DefaultBackend as OrmBackend>::Row;

/// Database handle, builder, backend-specific pool helpers, and runtime configuration.
pub mod db;
/// ORM runtime traits, filters, pagination, relation loading, schema models, and migrations.
pub mod graphql;
/// Common imports for applications using generated `graphql-orm` code.
pub mod prelude;
/// Shared scalar and input helper types used by generated GraphQL surfaces.
pub mod types;

/// Compile-time probes proving that certain generated APIs are deliberately absent.
///
/// These use `compile_fail` doctests instead of full-diagnostic snapshots so the assertions
/// hold across compiler versions regardless of rustc's error prose. Each probe is paired with
/// a compiling twin that differs only by the offending line, so a `compile_fail` success
/// cannot hide an unrelated breakage.
///
/// Append-only entities compile and expose reads:
///
/// ```
/// use graphql_orm::prelude::*;
///
/// #[derive(GraphQLEntity, GraphQLOperations, Clone, Debug, serde::Serialize, serde::Deserialize)]
/// #[graphql_entity(table = "events", plural = "Events", append_only = true)]
/// struct Event {
///     #[primary_key]
///     id: graphql_orm::uuid::Uuid,
///     #[filterable(type = "string")]
///     #[sortable]
///     kind: String,
/// }
///
/// async fn append(database: &Database<SqliteBackend>) -> graphql_orm::Result<()> {
///     let _ = Event::insert(database, CreateEventInput { kind: "created".to_string() }).await?;
///     Ok(())
/// }
/// ```
///
/// ...but generate no delete helper:
///
/// ```compile_fail
/// use graphql_orm::prelude::*;
///
/// #[derive(GraphQLEntity, GraphQLOperations, Clone, Debug, serde::Serialize, serde::Deserialize)]
/// #[graphql_entity(table = "events", plural = "Events", append_only = true)]
/// struct Event {
///     #[primary_key]
///     id: graphql_orm::uuid::Uuid,
///     #[filterable(type = "string")]
///     #[sortable]
///     kind: String,
/// }
///
/// async fn update(database: &Database<SqliteBackend>) {
///     let _ = Event::delete_all(database).await;
/// }
/// ```
///
/// Composite-key entities compile:
///
/// ```
/// use graphql_orm::prelude::*;
///
/// #[derive(GraphQLEntity, GraphQLOperations, Clone, Debug)]
/// #[graphql_entity(
///     backend = "sqlite",
///     table = "composite_write_records",
///     plural = "CompositeWriteRecords",
///     default_sort = "tenant_id ASC, local_id ASC"
/// )]
/// struct CompositeWriteRecord {
///     #[primary_key]
///     #[sortable]
///     pub tenant_id: i32,
///
///     #[primary_key]
///     #[sortable]
///     pub local_id: i32,
///
///     pub name: String,
/// }
///
/// fn main() {}
/// ```
///
/// ...but generate no single-key write helpers:
///
/// ```compile_fail
/// use graphql_orm::prelude::*;
///
/// #[derive(GraphQLEntity, GraphQLOperations, Clone, Debug)]
/// #[graphql_entity(
///     backend = "sqlite",
///     table = "composite_write_records",
///     plural = "CompositeWriteRecords",
///     default_sort = "tenant_id ASC, local_id ASC"
/// )]
/// struct CompositeWriteRecord {
///     #[primary_key]
///     #[sortable]
///     pub tenant_id: i32,
///
///     #[primary_key]
///     #[sortable]
///     pub local_id: i32,
///
///     pub name: String,
/// }
///
/// fn main() {
///     let _ = CompositeWriteRecord::create;
///     let _ = CompositeWriteRecord::update_by_id;
/// }
/// ```
#[cfg(all(feature = "sqlite", not(any(feature = "postgres", feature = "mssql"))))]
pub mod generated_api_absence_probes {}

/// Compile-time probes proving that MSSQL entities remain read-only.
///
/// These paired examples differ only by the write-helper reference. The first
/// proves the generated read-only entity itself compiles:
///
/// ```
/// use graphql_orm::prelude::*;
///
/// #[derive(GraphQLEntity, GraphQLOperations, Clone, Debug)]
/// #[graphql_entity(backend = "mssql", table = "dbo.LegacyJobs", plural = "Jobs")]
/// struct LegacyJob {
///     #[primary_key]
///     #[filterable(type = "string")]
///     pub id: String,
///
///     #[filterable(type = "string")]
///     #[sortable]
///     pub job_name: String,
/// }
///
/// fn main() {}
/// ```
///
/// ...while the second proves that no ordinary create helper is generated:
///
/// ```compile_fail
/// use graphql_orm::prelude::*;
///
/// #[derive(GraphQLEntity, GraphQLOperations, Clone, Debug)]
/// #[graphql_entity(backend = "mssql", table = "dbo.LegacyJobs", plural = "Jobs")]
/// struct LegacyJob {
///     #[primary_key]
///     #[filterable(type = "string")]
///     pub id: String,
///
///     #[filterable(type = "string")]
///     #[sortable]
///     pub job_name: String,
/// }
///
/// fn main() {
///     let _ = LegacyJob::create;
/// }
/// ```
#[cfg(all(feature = "mssql", not(any(feature = "sqlite", feature = "postgres"))))]
pub mod mssql_generated_api_absence_probes {}
